"""Book 1 exercise content — the parts of a unit the spec does not carry.

AI drafts, like the dialogues, until Innes replaces them. Each unit:
  match      six word–meaning pairs for the vocabulary page
  thread     a short text with six numbered gaps, its bank and key
  form/use/watch  the three rule cards
  practice   six grammar items with keys
  gist       two questions on the dialogue, with answers
  controlled six communication items with keys
  roleA/B    the role cards
  script     the In the Room listening, as (speaker, line)
  listen     four questions on it, with answers
  mini       the one-minute role-play
  pron       the pronunciation note
  ref        the grammar reference entry
"""

C = {}

C[1] = dict(
    match=[("assistant", "a person who helps a manager or a team"), ("founder", "the person who started the company"),
           ("colleague", "a person you work with"), ("remote", "working from home, not in the office"),
           ("surname", "your family name"), ("on site", "at the place where the work is")],
    thread=("Lena's new-starter form", [
        "First name: Lena · (1) ___: Hartmann", "Job: marketing (2) ___", "Country: (3) ___ · Nationality: German",
        "Today I am (4) ___ the office in Bristol.", "My (5) ___ is Sam Okafor, the founder.", "(6) ___ address: lena.hartmann@greenline.co.uk"],
        ["assistant", "boss", "email", "Germany", "in", "surname"], ["Surname", "assistant", "Germany", "in", "boss", "Email"]),
    form="*am / is / are*. I **am**, you **are**, he / she / it **is**, we / they **are**. Short forms: I'm, you're, she's, we're.",
    use="Say who people are, what their job is, where they are from and where they are now: *She's our new assistant. I'm from Hamburg. Tom is in the warehouse.*",
    watch="Questions put *be* first: *Are you in the office?* Negatives add *not*: *Tom isn't here. They aren't remote.*",
    practice=[("I ___ (be) from Hamburg.", "am"), ("She ___ (be) our new assistant.", "is"), ("Tom and Sam ___ (be) in Bristol.", "are"),
              ("___ you in the office? (be)", "Are"), ("Ana ___ (not be) in the office. She's at home.", "isn't"), ("We ___ (be) a small team.", "are")],
    gist=[("Where is Ana today?", "At home, in Valencia."), ("What does Priya need from Lena?", "The spelling of her surname, for her email.")],
    controlled=[("Hello, I ___ Lena. (am / is)", "am"), ("This ___ Ana. She ___ in sales. (is / are)", "is / is"), ("I ___ from Spain. I ___ Spanish. (am / is)", "am / am"),
                ("___ you remote today? (Are / Is)", "Are"), ("Tom ___ our driver. He ___ in the warehouse. (is / are)", "is / is"), ("We ___ in Bristol. They ___ in Valencia. (are / is)", "are / are")],
    roleA="You are new. It is your first video call. Say your name, your country, your job and where you are today. Then introduce the person next to you (Student B) to the team.",
    roleB="You are IT. Welcome the new person. Ask them to spell their surname and say their email address. Check one letter: *Is that one N or two?*",
    script=[("Priya", "Hi, this is Priya from IT. Can you spell your surname for me?"), ("Ben", "Sure. It's W-A-L-S-H. Walsh."),
            ("Priya", "W-A-L-S-H. Is that one L or two?"), ("Ben", "One L."), ("Priya", "Thanks. And your email is ben dot walsh at greenline dot co dot uk?"),
            ("Ben", "That's right. All small letters."), ("Priya", "Perfect. Welcome to Greenline, Ben.")],
    listen=[("What is Ben's surname?", "Walsh"), ("How many Ls?", "One"), ("What is his email address?", "ben.walsh@greenline.co.uk"), ("Are there capital letters in it?", "No, all small letters")],
    mini="Student A spells their real surname and says an email address. Student B writes it down and checks one letter. Swap. One minute each.",
    pron="Spell letters in groups of three: *H-A-R … T-M-A … N-N.* The voice goes up on each group and down on the last one. Say *double N* for two letters the same.",
    ref="**The verb *be*.** *I am, you are, he / she / it is, we are, they are.* Short forms are normal in speech: *I'm, you're, he's, we're, they're.* Negative: *I'm not, you aren't, she isn't.* Question: *Am I …? Are you …? Is she …?* Short answers: *Yes, I am. No, she isn't.* Use *be* for names, jobs, countries and places: *I'm Lena. She's an assistant. He's from Nigeria. They're in the warehouse.*",
)

C[2] = dict(
    match=[("time zone", "a region with the same clock time"), ("schedule", "a plan of times for the day or week"), ("early", "before the usual time"),
           ("have a break", "stop work for a short time"), ("an hour ahead", "one hour later on the clock"), ("finish", "stop work at the end of the day")],
    thread=("Lena's message to the team page", [
        "Hi! I (1) ___ work at nine and (2) ___ at half past five.", "I have (3) ___ at one o'clock.", "I'm in the office on Monday, Tuesday and Thursday.",
        "On Wednesday and Friday I work at (4) ___.", "Ana is one hour (5) ___ — she's in Spain.", "We have a (6) ___ every Monday at ten."],
        ["ahead", "call", "finish", "home", "lunch", "start"], ["start", "finish", "lunch", "home", "ahead", "call"]),
    form="I / you / we / they + verb: *I start, we finish, they work.* Negative with *don't*: *I don't have meetings.* Questions with *do*: *Do you work at home?*",
    use="Routines, habits and timetables: *I start at nine. We have lunch at two. They don't work on Fridays.*",
    watch="Time words: *at nine, at half past five, on Monday, in the morning, from ten to one.* *What time do you start?* — not *What time you start?*",
    practice=[("What time ___ you start? (do / does)", "do"), ("We ___ (not have) meetings on Mondays.", "don't have"), ("I ___ (finish) at six.", "finish"),
              ("___ they work at home on Fridays?", "Do"), ("Ana and I ___ (have) a call at ten.", "have"), ("You ___ (not start) early. (negative)", "don't start")],
    gist=[("What time does Ana start work?", "At eight."), ("When is the weekly call?", "Ten o'clock on Monday, UK time.")],
    controlled=[("I ___ at nine. (start / starts)", "start"), ("We ___ lunch at one. (have / has)", "have"), ("What time ___ you finish? (do / does)", "do"),
                ("They ___ work on Saturday. (don't / doesn't)", "don't"), ("Ana is one hour ___. (ahead / behind)", "ahead"), ("Nine in Bristol ___ ten in Valencia. (is / are)", "is")],
    roleA="You work in Bristol, nine to half past five, lunch at one. You are free on Tuesday morning. Find a weekly call time with Student B. Start the call: *Can you hear me?* End it.",
    roleB="You work in Valencia, eight to five, one hour ahead of Bristol. You have lunch at two and a meeting on Tuesday at eleven, your time. Find a time. End the call politely.",
    script=[("Ana", "Hi Tom! Can you hear me?"), ("Tom", "Yes — but I can't see you. Your camera is off."), ("Ana", "One second. Is that better?"),
            ("Tom", "Perfect. Shall we start?"), ("Ana", "Yes. Quick question: the van on Thursday — what time?"), ("Tom", "Ten in the morning, your time. Eleven."),
            ("Ana", "Eleven, OK. Great. I have another call now — bye!"), ("Tom", "Bye, Ana. See you on Monday.")],
    listen=[("What is the problem at the start?", "Tom can't see Ana — her camera is off."), ("What is the question about?", "The van on Thursday."),
            ("What time is the van, in Ana's time?", "Eleven."), ("Why does Ana end the call?", "She has another call.")],
    mini="Start a video call with Student B. Check sound and picture. Ask one question about the week. End the call. Swap.",
    pron="*Can you hear me?* — *can* is weak, *hear* is strong. *I CAN'T see you* — *can't* is strong. Say the times slowly: *half PAST five, quarter TO nine.*",
    ref="**Present simple, I / you / we / they.** Form: subject + verb: *I work, we start, they finish.* Negative: *don't* + verb: *I don't work on Fridays.* Question: *Do* + subject + verb: *Do you start at nine? What time do they finish?* Use it for routines, timetables and facts. Time phrases: *at* + clock time, *on* + day, *in* + the morning / afternoon, *from … to …*.",
)

C[3] = dict(
    match=[("charger", "you plug it in to give the laptop power"), ("password", "the secret word for your login"), ("frozen", "the screen stops and nothing moves"),
           ("printer", "it puts a document on paper"), ("cupboard", "you keep equipment in it"), ("update", "the new version of an app")],
    thread=("Lena's message to IT", [
        "Hi Priya! On my desk there (1) ___ a laptop and a keyboard, but there isn't a (2) ___.", "There (3) ___ two cables — I don't know what they are for.",
        "Is there a (4) ___ for the printer? I don't have one.", "Are there (5) ___ headphones in the cupboard?", "Also: my (6) ___ is frozen again! Thanks."],
        ["any", "are", "is", "mouse", "password", "screen"], ["is", "mouse", "are", "password", "any", "screen"]),
    form="*There is* + one thing: *There's a printer.* *There are* + more than one: *There are two screens.* Questions: *Is there …? Are there …?*",
    use="Say what exists and where. Use *some* in positive sentences: *There are some cables.* Use *any* in questions and negatives: *Is there any paper? There aren't any cups.*",
    watch="*There's* is not *it's*. *There's a printer* (it exists) — *It's a printer* (what it is). *Any* goes with plurals and uncountables: *any apps, any paper.*",
    practice=[("___ a printer in the office? (Is there / Are there)", "Is there"), ("There ___ some cables in the drawer.", "are"), ("There isn't ___ paper.", "any"),
              ("Are there ___ headphones?", "any"), ("There ___ a green light on the laptop.", "is"), ("There are ___ apps I need. (some / any)", "some")],
    gist=[("What is Lena's first problem?", "Her screen is frozen."), ("What does Priya tell her to do?", "Hold the power button for ten seconds.")],
    controlled=[("My screen ___ frozen. (is / are)", "is"), ("Can I ___ the chat app, please? (have / has)", "have"), ("___ there a second screen? (Is / Are)", "Is"),
                ("There ___ some in the cupboard. (is / are)", "are"), ("I don't have ___ passwords. (some / any)", "any"), ("Try ___: hold the button. (this / these)", "this")],
    roleA="It is your first day. Tell IT what there is on your desk and what there isn't. Ask for three things you need. One thing on your laptop doesn't work — say what.",
    roleB="You are IT. Listen, and tell Student A what to try: *Try this: …* Say where the things they need are: *There are some in the cupboard.* Ask: *Anything else?*",
    script=[("Tom", "Priya, the printer isn't working. There's a red light."), ("Priya", "OK. Is there any paper in it?"), ("Tom", "Er … no. There isn't any paper."),
            ("Priya", "There's some in the cupboard, on the left."), ("Tom", "Got it. … It's working now! Thanks."), ("Priya", "Anything else?"),
            ("Tom", "One more thing. Is there a new password for the Wi-Fi?"), ("Priya", "Yes. It's in your email.")],
    listen=[("What is wrong with the printer?", "It isn't working; there's a red light."), ("What is the real problem?", "There isn't any paper."),
            ("Where is the paper?", "In the cupboard, on the left."), ("What is Tom's second question?", "Is there a new Wi-Fi password?")],
    mini="Student A: your laptop has a problem — say what. Student B: give one thing to try. Then swap. One minute.",
    pron="*There's* sounds like *thairz*, one word. *Is there …?* — the voice goes up at the end. *It's working now!* — strong on *work*.",
    ref="**There is / there are; some / any.** *There is* (*there's*) with a singular or uncountable noun: *There's a laptop. There's some paper.* *There are* with a plural: *There are two screens.* Negative: *There isn't / There aren't.* Question: *Is there …? Are there …?* *Some* in positive sentences and offers; *any* in questions and negatives: *There are some cables. Are there any cups? There aren't any.*",
)

C[4] = dict(
    match=[("return", "a ticket there and back"), ("platform", "where you stand to get on the train"), ("direct", "the train doesn't stop or change"),
           ("opposite", "on the other side of the road"), ("go straight on", "don't turn"), ("take (an hour)", "it needs an hour")],
    thread=("A message from Mr Shaw", [
        "Hi Lena. Sam (1) ___ our office every month, so he knows the way.", "The train (2) ___ from Temple Meads at eight.", "It (3) ___ about ninety minutes and it doesn't (4) ___ in Bath.",
        "From the station, go out and turn (5) ___. We're on the right, (6) ___ the big café.", "See you on Thursday!"],
        ["left", "opposite", "stop", "takes", "leaves", "visits"], ["visits", "leaves", "takes", "stop", "left", "opposite"]),
    form="He / she / it: add *-s* or *-es*: *the train leaves, it stops, she goes, he watches.* Negative: *doesn't* + verb. Question: *Does* + subject + verb.",
    use="Timetables, facts and other people's routines: *It takes an hour. He visits them every month. Does it stop a lot?*",
    watch="After *doesn't* and *does*, no *-s*: *It doesn't stops* ✗ → *It doesn't stop* ✓. *Go, do, watch* take *-es*: *goes, does, watches.*",
    practice=[("The train ___ (leave) at eight.", "leaves"), ("It ___ (not stop) in Bath.", "doesn't stop"), ("___ Sam visit the customer every month? (Do / Does)", "Does"),
              ("A ticket ___ (cost) forty pounds.", "costs"), ("She ___ (go) by tram.", "goes"), ("The office is ___ the café. (opposite / at)", "opposite")],
    gist=[("How long does the train take?", "About an hour and a half."), ("Where is the customer's office?", "Near the station, on the right, opposite a big café.")],
    controlled=[("How do I ___ to the station? (get / go)", "get"), ("Go ___ of the station and turn left. (out / in)", "out"), ("Go ___ on for five minutes. (straight / right)", "straight"),
                ("It's on the right, ___ a café. (opposite / on)", "opposite"), ("Is it ___? — No, ten minutes on foot. (far / long)", "far"), ("You can't ___ it. (miss / lose)", "miss")],
    roleA="A colleague from another country is visiting your office next week. Tell them how to get there from the station: the way, how long it takes, and one thing they can't miss.",
    roleB="You are the visitor. Listen and repeat the directions back: *Left, then straight on …* Ask two questions: *Is it far? Does the bus stop there?*",
    script=[("Visitor", "Excuse me. How do I get to Greenline Office?"), ("Tom", "Go out of the station and turn right. Then go straight on for two minutes."),
            ("Visitor", "Right, then straight on."), ("Tom", "Yes. It's on the left, next to a small park. Opposite a bank."), ("Visitor", "Is it far?"),
            ("Tom", "No, five minutes on foot. You can't miss it — the door is green."), ("Visitor", "Green door. Thank you!")],
    listen=[("Does the visitor turn left or right?", "Right."), ("How long straight on?", "Two minutes."), ("What is opposite the office?", "A bank."), ("What colour is the door?", "Green.")],
    mini="Student A asks the way to a place in your town. Student B gives three directions. Student A repeats them back. Swap.",
    pron="*Turn LEFT. Go STRAIGHT on. It's on the RIGHT.* The direction word is strong. The *-s* on *leaves, takes* is a *z* sound; on *stops, costs* it is an *s* sound.",
    ref="**Present simple, he / she / it.** Add *-s* to the verb: *works, leaves, takes.* Add *-es* after *-o, -s, -sh, -ch, -x*: *goes, does, watches.* *Have* becomes *has.* Negative: *doesn't* + base verb: *It doesn't stop.* Question: *Does* + subject + base verb: *Does it stop?* **Prepositions of place and movement:** *from, to, at, in, on, near, next to, opposite, across.* *Go out of the station, turn left at the corner, it's opposite the café.*",
)

C[5] = dict(
    match=[("go running", "run for exercise"), ("relax", "rest and do nothing difficult"), ("weekday", "Monday to Friday"), ("hardly ever", "almost never"),
           ("healthy", "good for your body"), ("small talk", "easy, friendly talk before real business")],
    thread=("Ana's post on the well-being board", [
        "I (1) ___ go to the beach on Saturdays — it's five minutes away.", "I (2) ___ run! I hate running.", "In the week I'm (3) ___ busy, so I (4) ___ ever cook.",
        "We (5) ___ eat late in Spain, at nine or ten.", "On Sundays I (6) ___ relax with a book. It's my favourite day."],
        ["always", "hardly", "never", "often", "sometimes", "usually"], ["usually", "never", "always", "hardly", "often", "sometimes"]),
    form="*always · usually · often · sometimes · hardly ever · never.* Before a normal verb: *I usually go.* After *be*: *I'm always tired.*",
    use="Say how often you do things: *I often go to the beach. She hardly ever cooks in the week. We never run.*",
    watch="*I go always running* ✗ — the adverb goes before the verb: *I always go running.* But after *am / is / are*: *He is never late.*",
    practice=[("I go running on Saturdays. (usually)", "I usually go running on Saturdays."), ("She is late. (never)", "She is never late."), ("We eat late. (often)", "We often eat late."),
              ("I am at the gym on Sundays. (always)", "I am always at the gym on Sundays."), ("They cook in the week. (hardly ever)", "They hardly ever cook in the week."), ("Do you watch films? (sometimes)", "Do you sometimes watch films?")],
    gist=[("What does Lena do on Saturdays?", "She usually goes running."), ("Why doesn't Lena cook in the week?", "She is too tired.")],
    controlled=[("How ___ your weekend? (was / is)", "was"), ("Oh, ___? (really / real)", "really"), ("That ___ nice. (sounds / sound)", "sounds"),
                ("I know what you ___. (mean / say)", "mean"), ("___ here. (Same / Some)", "Same"), ("Right, here's Sam. ___ start. (Let's / Let)", "Let's")],
    roleA="You are early for a call with a colleague you don't know well. Ask about their weekend. Show interest three times: *Really? That sounds nice. Same here.* Say what you usually do at the weekend.",
    roleB="Answer Student A's questions about your weekend. Ask two questions back. When 'the boss' arrives, say: *Right, let's start.*",
    script=[("Tom", "Morning, Priya. How was your weekend?"), ("Priya", "Good, thanks. I played football on Saturday."), ("Tom", "Oh, really? I never play. I usually watch it!"),
            ("Priya", "That sounds relaxing. And Sunday I cooked for my parents."), ("Tom", "Nice. I hardly ever cook. Too tired."), ("Priya", "Same here in the week. Oh — here's Sam."),
            ("Tom", "Right. Let's start.")],
    listen=[("What did Priya do on Saturday?", "She played football."), ("Does Tom play football?", "No, never — he usually watches it."), ("What did Priya do on Sunday?", "She cooked for her parents."), ("Who arrives at the end?", "Sam.")],
    mini="One minute of small talk before a meeting: Student A asks about the weekend, Student B answers, both show interest. Swap.",
    pron="Show interest with your voice: *Oh, REALLY?* goes up. *That's GREAT.* goes down. *Same here* is quick and friendly — don't stress *here*.",
    ref="**Adverbs of frequency.** *always (100%) · usually · often · sometimes · hardly ever · never (0%).* Position: before the main verb (*I usually start at nine*), after *be* (*She is always early*), and between *don't / doesn't* and the verb (*I don't often cook*). *Sometimes* can also start a sentence: *Sometimes I cook.* Question: *How often do you …? — Every day. Once a week. Twice a month.*",
)

C[6] = dict(
    match=[("founder", "the person who started the company"), ("milestone", "an important moment in a history"), ("the first office", "where the company began"),
           ("ago", "before now: two years ago"), ("product", "a thing a company makes and sells"), ("sales", "the money from things a company sells")],
    thread=("The 'Our story' box on the website", [
        "Greenline (1) ___ in two thousand and fifteen.", "The founder (2) ___ Sam Okafor. He was thirty-one.", "The first office (3) ___ a garage. There (4) ___ two people: Sam and Tom.",
        "The first (5) ___ was a desk. The price was ninety-nine pounds.", "In twenty twenty, everybody was at home, and (6) ___ were very big."],
        ["product", "sales", "started", "was", "was", "were"], ["started", "was", "was", "were", "product", "sales"]),
    form="*was* for I / he / she / it; *were* for you / we / they. Negative: *wasn't, weren't.* Question: *Was it …? Were you …?*",
    use="Talk about the past with *be*: where, when, who, how old: *The first office was a garage. There were two people. Were you at home in twenty twenty?*",
    watch="Years: *two thousand and fifteen* or *twenty fifteen* — both fine. *Nineteen ninety-nine*, not *one thousand nine hundred …* Prices: *ninety-nine pounds*.",
    practice=[("The first office ___ a garage.", "was"), ("There ___ two people.", "were"), ("___ you at home in twenty twenty?", "Were"),
              ("The price ___ (not) high.", "wasn't"), ("Tom and Sam ___ the first team.", "were"), ("___ it a big year? — Yes, it ___.", "Was / was")],
    gist=[("When did Greenline start, and where?", "In 2015, in Sam's garage."), ("Why was 2020 a big year?", "Everybody was at home and sales were very big.")],
    controlled=[("Two thousand ___ fifteen. (and / –)", "and"), ("Ninety-nine — nine, ___. (nine / ninety)", "nine"), ("Sorry — how ___ was it? (much / many)", "much"),
                ("Two ___ and forty pounds. (hundred / hundreds)", "hundred"), ("So that ___ the big year. (was / were)", "was"), ("How ___ people were there? (many / much)", "many")],
    roleA="Tell Student B the history of a company or place you know: when it started, who the founder was, where the first office was, what the first product was. Say every year and number in words.",
    roleB="Listen and check every number: *Sorry, how many? Two thousand and …?* Then write three facts you heard.",
    script=[("Lena", "Sam, when was the first shop?"), ("Sam", "Twenty nineteen. In Bath. It was very small."), ("Lena", "Twenty nineteen. And how many chairs were there on day one?"),
            ("Sam", "Twelve. And one desk!"), ("Lena", "Sorry — one-two, twelve?"), ("Sam", "Yes, twelve. The desk was two hundred pounds."), ("Lena", "Two hundred. So that was the first shop.")],
    listen=[("When was the first shop?", "2019."), ("Where was it?", "In Bath."), ("How many chairs were there?", "Twelve."), ("How much was the desk?", "Two hundred pounds.")],
    mini="Student A says four years and prices. Student B writes them and checks two: *Sorry, nineteen ninety or nineteen nineteen?* Swap.",
    pron="Years in two halves: *twenty | fifteen, nineteen | ninety-nine.* Prices: *ninety-NINE pounds.* Check a number by saying the digits: *nine, nine.*",
    ref="**Past simple of *be*.** *I / he / she / it was; you / we / they were.* Negative: *wasn't, weren't.* Question: *Was he …? Were they …?* Short answers: *Yes, it was. No, they weren't.* *There was / there were* for the past: *There was one desk. There were two people.* **Years and numbers:** *two thousand and fifteen* / *twenty fifteen*; *nineteen ninety-nine*; *two hundred and forty*; *one thousand two hundred*.",
)

C[7] = dict(
    match=[("arrive", "get to a place"), ("meet", "see a person for the first time"), ("catalogue", "a book of products and prices"), ("on time", "not late"),
           ("finally", "the last thing"), ("come back", "return")],
    thread=("Lena's report to Sam", [
        "Hi Sam. First, I (1) ___ the eight o'clock train. It (2) ___ on time.", "Then I (3) ___ to the office and (4) ___ Mr Shaw.",
        "He (5) ___ the new chairs and asked about prices. I gave him a catalogue.", "After that, we (6) ___ lunch. Finally, I came home at six.", "Next step: an email with prices. Lena"],
        ["arrived", "had", "liked", "met", "took", "walked"], ["took", "arrived", "walked", "met", "liked", "had"]),
    form="Regular verbs: *-ed*: *walked, liked, wanted.* Irregular verbs: learn them: *take → took, meet → met, give → gave, have → had, come → came, say → said.*",
    use="Finished actions in the past: *I took the train. He asked about prices. We had lunch.* Show the order: *first, then, after that, finally.*",
    watch="Questions and negatives use *did* + base verb: *Did you give him one?* not *Did you gave*. *He didn't like* not *He didn't liked*.",
    practice=[("I ___ (take) the train.", "took"), ("She ___ (meet) the manager.", "met"), ("___ you ___ (send) the email?", "Did … send"),
              ("He ___ (not like) the chairs.", "didn't like"), ("We ___ (have) lunch at one.", "had"), ("They ___ (arrive) on time.", "arrived")],
    gist=[("What did Mr Shaw want?", "A catalogue."), ("What is the next step?", "An email to Mr Shaw.")],
    controlled=[("___, I took the train. (First / One)", "First"), ("___ I walked to the office. (Then / After)", "Then"), ("___ that, we had lunch. (After / Then)", "After"),
                ("___, I came home at six. (Finally / Final)", "Finally"), ("And ___? (then / after)", "then"), ("What happened ___? (next / after)", "next")],
    roleA="Tell Student B about a trip or a visit you made. Use *first, then, after that, finally* and at least six past-tense verbs.",
    roleB="Listen. Ask *And then? What happened next?* twice. At the end, say the four steps back to Student A in order.",
    script=[("Sam", "Tom, how was the delivery in Cardiff?"), ("Tom", "Good. First I loaded the van at seven. Then I drove for two hours."), ("Sam", "And then?"),
            ("Tom", "I arrived at ten and met the customer. She liked the desks."), ("Sam", "Did she order more?"), ("Tom", "Yes — ten chairs. After that I had a coffee, and finally I came back at three.")],
    listen=[("What time did Tom load the van?", "At seven."), ("How long did he drive?", "Two hours."), ("What did the customer order?", "Ten chairs."), ("When did Tom come back?", "At three.")],
    mini="Student A tells yesterday in four steps with *first, then, after that, finally*. Student B asks *And then?* once. Swap.",
    pron="*-ed* has three sounds: *walked* (t), *arrived* (d), *wanted* (id). Sequence words are strong and followed by a small pause: *FIRST, | I took the train.*",
    ref="**Past simple.** Regular verbs add *-ed*: *walk → walked, like → liked, want → wanted.* Irregular verbs change: *take → took, meet → met, give → gave, have → had, come → came, go → went, say → said, do → did.* Negative: *didn't* + base verb: *He didn't like it.* Question: *Did* + subject + base verb: *Did you send it?* **Sequence:** *first, then, next, after that, finally.*",
)

C[8] = dict(
    match=[("work on", "spend time doing a task"), ("update", "the latest news about a task"), ("deadline", "the day the work must be finished"),
           ("in progress", "started, not finished"), ("spreadsheet", "a page of numbers in columns"), ("no rush", "it isn't urgent")],
    thread=("Lena's update in the team chat", [
        "Quick update! I'm (1) ___ on the history page. I'm (2) ___ the text now.", "Tom is (3) ___ twenty desks for a school. The van is coming at two.",
        "Ana is (4) ___ the hotel in Madrid.", "I'm (5) ___ for the photos from Jo.", "One problem: my spreadsheet isn't (6) ___. Priya is helping."],
        ["calling", "packing", "waiting", "working", "working", "writing"], ["working", "writing", "packing", "calling", "waiting", "working"]),
    form="*am / is / are* + verb + *-ing*: *I'm writing, she's calling, they're packing.* Negative: *isn't working.* Question: *What are you working on?*",
    use="Things happening now, or around now: *I'm writing the new page. The van is coming at two. Everybody's busy.*",
    watch="Spelling: *write → writing, come → coming, sit → sitting, run → running.* Present simple for habits (*I write every day*); continuous for now (*I'm writing now*).",
    practice=[("I ___ (write) the new page.", "'m writing"), ("What ___ you ___ (work) on?", "are … working"), ("The van ___ (come) at two.", "is coming"),
              ("They ___ (not pack) the chairs yet.", "aren't packing"), ("___ she ___ (call) the hotel now?", "Is … calling"), ("We ___ (wait) for the photos.", "'re waiting")],
    gist=[("What is Tom's team doing?", "Packing twenty desks for a school."), ("What is Lena's problem?", "Her spreadsheet isn't working — the numbers aren't adding up.")],
    controlled=[("Can you ___ me with something? (help / helping)", "help"), ("Sure. What's the ___? (problem / matter)", "problem"), ("Give me two ___. (minutes / minute)", "minutes"),
                ("I'm just ___ an email. (finishing / finish)", "finishing"), ("No ___. (rush / hurry)", "rush"), ("Ah, I ___. (see / look)", "see")],
    roleA="Your manager (Student B) stops at your desk. Say what you are working on, what you are not doing yet, and ask for help with one thing.",
    roleB="You are the manager. Ask *What are you working on?* Listen, then ask one more question. When Student A asks for help, say *Sure — give me two minutes.*",
    script=[("Ana", "Priya, can you help me with something?"), ("Priya", "Sure. What's the problem?"), ("Ana", "The video app isn't working. I'm calling the hotel in ten minutes."),
            ("Priya", "Ah, I see. Is it updating?"), ("Ana", "Yes — there's a blue bar."), ("Priya", "OK, it's installing the update. Give it two minutes."), ("Ana", "Thanks, Priya. No rush — I have eight minutes!")],
    listen=[("What isn't working?", "The video app."), ("When is Ana's call?", "In ten minutes."), ("What is the app doing?", "Installing an update."), ("How long does Priya say to wait?", "Two minutes.")],
    mini="Student A asks Student B for help with one task. Student B says yes and asks one question. One minute. Swap.",
    pron="*-ing* is one sound, no *g*: *writ-ing, call-ing.* Contractions are normal: *I'm, she's, they're.* *Can you HELP me with something?* — *help* is strong.",
    ref="**Present continuous.** *am / is / are* + verb + *-ing*. *I'm writing, you're packing, he's calling, we're waiting.* Negative: *isn't / aren't* + *-ing*. Question: *Are you working? What is she doing?* Use it for actions happening now and for things that are temporary around now. Spelling: drop *-e* (*come → coming*); double a final consonant after one short vowel (*sit → sitting*).",
)

C[9] = dict(
    match=[("supplier", "a company that sells to your company"), ("quality", "how good something is"), ("delivery", "when the things arrive"),
           ("expensive", "it costs a lot"), ("recycled", "made from old material again"), ("option", "one of the things you can choose")],
    thread=("Lena's note to Sam", [
        "Hi Sam. Two box suppliers. Box A is (1) ___ — two pounds. Box B is three pounds, so it's (2) ___ expensive.",
        "But B is (3) ___ and it's recycled. I think the (4) ___ is better.", "A is (5) ___ — two days, not a week.",
        "In my (6) ___, B is the better box. The customer sees the box first. Lena"],
        ["cheaper", "faster", "more", "opinion", "quality", "stronger"], ["cheaper", "more", "stronger", "quality", "faster", "opinion"]),
    form="Short adjectives + *-er*: *cheap → cheaper, fast → faster, big → bigger, nice → nicer.* Long adjectives: *more* + adjective: *more expensive.* Irregular: *good → better, bad → worse.*",
    use="Compare two things: *This box is cheaper. The other one is stronger. Recycled is better for us.* Add *than* for the second thing: *B is more expensive than A.*",
    watch="*More cheaper* ✗ — one comparative only. *Big → bigger* (double the g). *Than*, not *that*: *faster than a week.*",
    practice=[("This box is ___ (cheap).", "cheaper"), ("Recycled card is ___ (good) for us.", "better"), ("The other supplier is ___ (expensive).", "more expensive"),
              ("Two days is ___ (fast) than a week.", "faster"), ("A big van is ___ (bad) for the city.", "worse"), ("The new desk is ___ (big) than the old one.", "bigger")],
    gist=[("Which box is cheaper, and by how much?", "The first one, by one pound a box."), ("Why does Lena prefer the recycled box?", "The customer sees the box first, and recycled is better for the company.")],
    controlled=[("I ___ the recycled one is better. (think / thinking)", "think"), ("In my ___, B is nicer. (opinion / mind)", "opinion"), ("I'm not ___. (sure / certain)", "sure"),
                ("Good ___. (point / idea)", "point"), ("Yes, ___ three pounds is a lot. (but / and)", "but"), ("Which one do you ___? (prefer / like)", "prefer")],
    roleA="Choose a chat app for the team. App 1 is free and simple. App 2 costs money and does more. Compare them in five sentences and give your opinion.",
    roleB="Listen. Disagree once, politely: *Yes, but …* Then agree: *Good point.* Say which one you prefer and why.",
    script=[("Sam", "Two vans. Tom, which one?"), ("Tom", "The small one is cheaper and it's easier to park in town."), ("Sam", "Yes, but the big one carries more desks."),
            ("Tom", "Good point. But it's more expensive — and slower."), ("Sam", "I'm not sure. Is the small one strong enough?"), ("Tom", "I think so. In my opinion, the small one is better for us."),
            ("Sam", "OK. Let's ask Lena.")],
    listen=[("Why does Tom like the small van?", "It's cheaper and easier to park."), ("What is good about the big van?", "It carries more desks."), ("What is bad about the big van?", "It's more expensive and slower."), ("Who do they ask at the end?", "Lena.")],
    mini="Student A compares two phones in three sentences and gives an opinion. Student B disagrees once, then agrees. Swap.",
    pron="*-er* is weak: *CHEAP-er, FAST-er.* *Than* is weak too: *faster th'n a week.* *I THINK …* and *in MY opinion* — stress the opinion word.",
    ref="**Comparatives.** One syllable: add *-er* (*cheaper, faster*); double the last letter after one short vowel (*bigger, hotter*); *-y → -ier* (*easier*). Two or more syllables: *more* + adjective (*more expensive, more difficult*). Irregular: *good → better, bad → worse, far → further.* *Than* joins the two things: *B is stronger than A.* Make it bigger or smaller: *much cheaper, a bit faster.*",
)

C[10] = dict(
    match=[("recycle", "use old material to make something new"), ("bin", "the container for rubbish"), ("switch off", "turn the power off"),
           ("refill", "fill your bottle or cup again"), ("rule", "what you can and can't do"), ("waste", "things you throw away")],
    thread=("The green rules poster", [
        "1 You (1) ___ recycle paper and card — blue bin.", "2 You (2) ___ put plastic in the blue bin. Plastic goes in the green one.",
        "3 You can bring your own (3) ___. There are no paper cups.", "4 Please (4) ___ off the lights at night.",
        "5 You (5) ___ open the windows in summer.", "6 We don't use plastic (6) ___. It's a company rule."],
        ["bags", "can", "can", "can't", "cup", "switch"], ["can", "can't", "cup", "switch", "can", "bags"]),
    form="*can* + base verb for all persons: *I can, she can, they can.* Negative: *can't* (*cannot*). Question: *Can I …? Can we …?*",
    use="Rules and permission: *You can recycle paper here* (it's allowed). *You can't leave the lights on* (it's not allowed). *Can I bring my own cup?* (asking permission).",
    watch="No *to* after *can*: *You can to bring* ✗. No *-s*: *She cans* ✗. Short answers: *Yes, you can. No, you can't.*",
    practice=[("You ___ recycle paper in the blue bin. (yes)", "can"), ("You ___ put plastic there. (no)", "can't"), ("___ I bring my own cup?", "Can"),
              ("We ___ use plastic bags. It's a rule. (no)", "can't"), ("Yes, you ___.", "can"), ("___ we open the windows in winter? — No, you ___.", "Can / can't")],
    gist=[("Which bin is for plastic?", "The green bin."), ("What does the supplier offer, and what does Tom say?", "Free plastic bags; Tom says no — it's a company rule.")],
    controlled=[("Thanks, but no ___. (thanks / thank)", "thanks"), ("I'm sorry, ___ no. (but / and)", "but"), ("Thank you ___ the offer. (for / to)", "for"),
                ("It's a company ___. (rule / law)", "rule"), ("Maybe ___ time. (another / other)", "another"), ("That's ___, but we can't. (kind / kindly)", "kind")],
    roleA="A new colleague (Student B) asks about the green rules in your office. Explain five things they can and can't do. Then Student B offers you free plastic pens with your logo — say no politely, twice.",
    roleB="Ask Student A three questions with *Can I …?* about the office. Then you are a supplier: offer free plastic pens. When they say no, try once more: *But they're free!*",
    script=[("Supplier", "Hi Tom! Good news. We have free plastic cups for your office. Five hundred!"), ("Tom", "That's kind, but we can't use plastic cups."),
            ("Supplier", "They're free."), ("Tom", "I know. It's a company rule — everybody brings their own cup."), ("Supplier", "What about plastic bags?"),
            ("Tom", "I'm sorry, but no. Thank you for the offer. Maybe another time — if they're paper!")],
    listen=[("What does the supplier offer first?", "Five hundred free plastic cups."), ("Why can't Tom take them?", "It's a company rule — everybody brings their own cup."), ("What does the supplier offer next?", "Plastic bags."), ("When could Tom say yes?", "If they're paper.")],
    mini="Student A offers Student B something free that they don't want. Student B says no politely, three different ways. Swap.",
    pron="*Can* is weak before a verb: *You c'n bring a cup.* *Can't* is strong: *You CAN'T put plastic there.* Say no with a warm voice: *I'm SORRY, but no.*",
    ref="**Can and can't for rules and permission.** *can* + base verb, the same for every person: *I can, she can, we can.* Negative: *can't* (*cannot*). Question: *Can I …? Can we …?* Short answers: *Yes, you can. No, you can't.* *Can* also means ability (*I can drive*) — see Book 2. For requests, see Unit 11: *Can you …? Could you …?*",
)

C[11] = dict(
    match=[("damaged", "broken a little"), ("missing", "not there"), ("delayed", "late"), ("replacement", "a new one instead of the broken one"),
           ("order number", "the number of your order"), ("apologise", "say sorry")],
    thread=("Tom's email to Mr Shaw", [
        "Dear Mr Shaw, I'm really sorry (1) ___ the desk. The top is (2) ___.", "I also (3) ___ for the delay — Friday, not Thursday.",
        "Two chairs are (4) ___. We know — they are in the van now.", "(5) ___ you keep the broken desk until Monday? We bring a (6) ___.", "Sorry again. Tom"],
        ["about", "apologise", "Could", "damaged", "missing", "replacement"], ["about", "damaged", "apologise", "missing", "Could", "replacement"]),
    form="Requests: *Can you …? Could you …?* + base verb. *Could* is a little more polite. For yourself: *Can I …? Could I …?*",
    use="Ask people to do things: *Can you check the order number? Could you send me a photo? Could I call you back?*",
    watch="Answer a request with *Sure / Of course / Yes, one minute* — not just *Yes, I can*. Say sorry *about* a thing, *for* an action: *sorry about the desk, sorry for the delay.*",
    practice=[("___ you send me a photo? (Could / Are)", "Could"), ("___ I call you back? (Can / Do)", "Can"), ("I'm really sorry ___ the desk. (about / for)", "about"),
              ("Don't ___ about it. (worry / sorry)", "worry"), ("I apologise ___ the delay. (for / about)", "for"), ("___ you keep it until Monday? (Could / Should)", "Could")],
    gist=[("What are the three problems with Mr Shaw's order?", "A damaged desk, two missing chairs, a late delivery."), ("What does Tom ask Mr Shaw to do?", "Keep the desk until Monday.")],
    controlled=[("I'm really ___ about the desk. (sorry / sad)", "sorry"), ("Don't worry ___ it. (about / for)", "about"), ("These things ___. (happen / happens)", "happen"),
                ("No problem ___ all. (at / of)", "at"), ("It's not your ___. (fault / problem)", "fault"), ("Sorry ___. (again / more)", "again")],
    roleA="You are Mr Shaw. Call Greenline. Say what is wrong with your order (three things) and ask for two things. When Tom apologises, accept the apology.",
    roleB="You are Tom. Listen, ask for the order number and a photo, apologise for each problem, and offer a solution with a day.",
    script=[("Customer", "Hello, this is Mrs Rees. My lamp arrived, but it's the wrong colour. I ordered green."), ("Ana", "I'm really sorry about that. Could you give me the order number?"),
            ("Customer", "GL two-three-one-eight."), ("Ana", "Thank you. Yes — I see the mistake. It's our fault. Can I send a green one today?"), ("Customer", "Yes, please. And the blue one?"),
            ("Ana", "Keep it. No charge. I apologise for the trouble."), ("Customer", "That's fine. These things happen.")],
    listen=[("What is wrong with the order?", "The lamp is the wrong colour — blue, not green."), ("What is the order number?", "GL 2318."), ("What does Ana offer?", "A green lamp today, and the customer keeps the blue one free."), ("How does the customer accept the apology?", "That's fine. These things happen.")],
    mini="Student A apologises for a small problem at work. Student B accepts the apology. Swap. Use three different phrases.",
    pron="*Could you …?* — the *d* and *y* join: *cou-dyou*. *I'm REALLY sorry* — stress *really*. *Don't WORRY about it* — friendly and quick.",
    ref="**Requests with *can* and *could*.** *Can you …? / Could you …?* + base verb ask someone to do something; *could* is softer. *Can I …? / Could I …?* ask for permission or offer to do something yourself. Answers: *Sure. Of course. Yes, one minute. I'm afraid I can't.* **Apologising:** *I'm (really) sorry about* + noun; *I'm sorry for* + -ing / noun; *I apologise for …* **Accepting:** *Don't worry about it. That's fine. No problem at all. These things happen.*",
)

C[12] = dict(
    match=[("appointment", "a time you agree to meet"), ("invite", "the calendar message for a meeting"), ("available", "free at that time"),
           ("cancel", "say the meeting will not happen"), ("move", "change the meeting to another time"), ("confirm", "say yes, that's right")],
    thread=("The calendar invite", [
        "What: Photo shoot for the new website", "When: (1) ___ 6 May, 2 p.m.", "Where: the warehouse, Bristol",
        "Who: Jo (photographer), Lena, Tom", "Notes: Jo is (2) ___ two lights. We're (3) ___ at two, not nine — Sam is (4) ___ a customer in the morning.",
        "Please (5) ___ by Friday. Thanks for being (6) ___! Lena"],
        ["bringing", "confirm", "flexible", "meeting", "Tuesday", "visiting"], ["Tuesday", "bringing", "meeting", "visiting", "confirm", "flexible"]),
    form="*am / is / are* + verb + *-ing* with a future time: *We're meeting at nine on the sixth. I'm working in London that day.*",
    use="Arrangements — things in the diary with a time and a place: *Are you free on the fifth? I'm bringing two lights. Sam is visiting a customer on Monday.*",
    watch="Dates: *on the fifth of May* / *on May the fifth*. Say *the fifth*, *the sixth*, *the twenty-first*. *Next month* has no *on*.",
    practice=[("We ___ (do) a photo shoot next month.", "'re doing"), ("___ you free on the fifth? (Are / Do)", "Are"), ("I ___ (work) in London that day.", "'m working"),
              ("Sam ___ (visit) a customer on Monday.", "is visiting"), ("Can we ___ it to two? (move / moving)", "move"), ("Jo ___ (bring) two lights.", "is bringing")],
    gist=[("Why can't Jo do the fifth?", "She's working in London that day."), ("Why does Lena change the time?", "Sam is visiting a customer on the sixth in the morning.")],
    controlled=[("Are you ___ on the fifth? (free / busy)", "free"), ("Does the afternoon ___? (work / go)", "work"), ("Can we ___ the time? (change / move on)", "change"),
                ("Sorry, there's a problem ___ the date. (with / of)", "with"), ("Two is ___. (fine / good one)", "fine"), ("Thanks for being ___. (flexible / free)", "flexible")],
    roleA="Arrange a photo shoot with a photographer (Student B) for next month: the date, the time, the place, what they are bringing. Then call back and change the time.",
    roleB="You are the photographer. You are not free on the first date Student A says. Suggest another day. Ask about parking. When they change the time, be flexible.",
    script=[("Jo", "Hi Lena, it's Jo. Quick one — are we still meeting on the sixth?"), ("Lena", "Yes, at two. Is that OK?"), ("Jo", "Sorry, there's a problem with the time. I'm shooting in Bath until three."),
            ("Lena", "No problem. Does four work?"), ("Jo", "Four is fine. And I'm bringing a second camera."), ("Lena", "Great. I'm sending a new invite now."), ("Jo", "Thanks for being flexible!")],
    listen=[("When is the shoot?", "On the sixth."), ("Why can't Jo come at two?", "She's shooting in Bath until three."), ("What time do they agree?", "Four."), ("What is Jo bringing?", "A second camera.")],
    mini="Student A has a meeting in the diary with Student B. Call and change the time politely. Student B agrees and asks for a new invite. Swap.",
    pron="Dates: *the SIXTH of MAY*. *Are you FREE on the fifth?* goes up at the end. *Two is FINE.* goes down — it's a decision.",
    ref="**Present continuous for arrangements.** *am / is / are* + *-ing* with a future time word: *We're meeting at nine tomorrow. She's working in London on Friday. Are you coming on the sixth?* Use it for plans that are fixed in a diary, with people, times and places. (For intentions with no fixed time, use *going to* — Unit 15.) **Dates:** *on the fifth of May, on Monday the sixth, next week, next month, in the morning / afternoon.*",
)

C[13] = dict(
    match=[("invoice", "the paper that says what you must pay"), ("quantity", "how many"), ("total", "all the money together"), ("discount", "a lower price"),
           ("furniture", "desks, chairs, tables — uncountable"), ("confirm", "say that something is right")],
    thread=("The order confirmation", [
        "Dear Hotel Sol, thank you for your (1) ___.", "Chairs: forty (40) at one hundred and sixty-eight euros (2) ___.",
        "Small desks: twelve (12) at two hundred and forty euros each.", "(3) ___: nine thousand six hundred euros. Delivery: free.",
        "We need (4) ___ information: your invoice address and a phone number.", "How (5) ___ days for delivery? About ten. Please (6) ___ the address. Ana"],
        ["confirm", "each", "many", "order", "some", "Total"], ["order", "each", "Total", "some", "many", "confirm"]),
    form="Countable nouns have a plural: *a chair, forty chairs.* Uncountable nouns have no plural: *money, information, furniture, time.* *How many* + countable; *how much* + uncountable.",
    use="Ask about quantity and price: *How many chairs do you need? How much is the desk? How much is delivery?* Offers and requests: *some*. Questions and negatives: *any*.",
    watch="*Informations* ✗, *furnitures* ✗. *How much is it?* asks the price. *A lot of* works with both.",
    practice=[("How ___ chairs do you need?", "many"), ("How ___ is delivery?", "much"), ("Do you need ___ information?", "any"),
              ("Yes, ___ details, please.", "some"), ("How ___ money is that?", "much"), ("We don't have ___ desks in stock. (some / any)", "any")],
    gist=[("What does the hotel order?", "Forty chairs and twelve small desks."), ("What does Ana ask for at the end?", "The invoice address and a phone number.")],
    controlled=[("___ me check: forty chairs. (Let / Leave)", "Let"), ("One-two, twelve, ___ two-zero, twenty? (or / and)", "or"), ("So the ___ is nine thousand. (total / all)", "total"),
                ("Sorry, how ___? (much / many)", "much"), ("Did you say fifteen ___ fifty? (or / and)", "or"), ("Can you ___ the address? (confirm / sure)", "confirm")],
    roleA="You are a hotel. Order chairs and desks for a meeting room from Student B. Ask two prices. Confirm the total. Give an invoice address with a house number.",
    roleB="You are sales. Ask *How many …?* and give prices. Read the order back. Check one number: *Is that fifteen or fifty?* Confirm the total.",
    script=[("Customer", "I'd like to order some lamps. Fifteen."), ("Ana", "Fifteen — one-five?"), ("Customer", "Yes, one-five. How much are they?"), ("Ana", "Sixty euros each. So nine hundred euros."),
            ("Customer", "And delivery?"), ("Ana", "Delivery is thirty euros. Total: nine hundred and thirty."), ("Customer", "Nine thirty. OK. Do you need any information?"), ("Ana", "Yes — can you confirm the address?")],
    listen=[("How many lamps?", "Fifteen."), ("How much is one lamp?", "Sixty euros."), ("How much is delivery?", "Thirty euros."), ("What is the total?", "Nine hundred and thirty euros.")],
    mini="Student A orders three things with quantities. Student B reads the order back and checks two numbers. Swap.",
    pron="Check a number by saying the digits: *one-two, twelve.* Big numbers in groups: *nine THOUSAND | six HUNDRED.* *How MUCH is it?* — *much* is strong.",
    ref="**Countable and uncountable nouns.** Countable: *a chair / chairs, an invoice / invoices.* Uncountable, no plural, no *a*: *money, information, furniture, time, paper, advice.* *How many* + plural countable: *How many desks?* *How much* + uncountable: *How much money? How much is it?* (price). *Some* in positive sentences and offers; *any* in questions and negatives. *A lot of* with both.",
)

C[14] = dict(
    match=[("visitor", "a person who comes to see you"), ("showroom", "the room where you show products"), ("reception", "the desk at the entrance"),
           ("offer", "say 'Would you like …?'"), ("comfortable", "relaxed, at ease"), ("guest", "another word for visitor")],
    thread=("The welcome message for Ben's first video call", [
        "Hi everyone! This is Ben, our new sales rep. (1) ___ to the team, Ben!", "Ben, this call is just hello. Make yourself (2) ___.",
        "Can everyone (3) ___ Ben? Say hi!", "(4) ___ you like to say something, Ben?", "Ana is (5) ___ Ben around the office next week.", "Would you like a coffee first? (6) ___ your own cup!"],
        ["Bring", "comfortable", "see", "showing", "Welcome", "Would"], ["Welcome", "comfortable", "see", "Would", "showing", "Bring"]),
    form="*Would you like* + noun: *Would you like a coffee?* *Would you like to* + verb: *Would you like to see the showroom?* Answer: *I'd like a coffee, please. I'd like to see it.*",
    use="Polite offers and polite wishes: *Would you like tea or coffee? I'd like a coffee, please. I'd like to say thank you.*",
    watch="*Would you like* is an offer; *Do you like* is about taste in general. *I'd like* = *I would like*: polite. *I want* is stronger and less polite with a visitor.",
    practice=[("___ you like a coffee?", "Would"), ("I'___ like a tea, please.", "d"), ("Would you like ___ see the showroom? (to / –)", "to"),
              ("___ I take your coat? (Can / Would)", "Can"), ("Please, have a ___. (seat / sit)", "seat"), ("Would you like ___ (say) something?", "to say")],
    gist=[("What does Mr Shaw want to see first?", "The showroom."), ("Who is Ben?", "The new sales rep, welcomed on the Monday call.")],
    controlled=[("___ to Greenline. Come in. (Welcome / Welcoming)", "Welcome"), ("Please, ___ a seat. (have / take)", "have"), ("Can I ___ your coat? (take / have)", "take"),
                ("Make yourself ___. (comfortable / comfort)", "comfortable"), ("Help ___ to biscuits. (yourself / you)", "yourself"), ("Is the room OK — not too ___? (warm / hot one)", "warm")],
    roleA="A visitor (Student B) arrives ten minutes early for a meeting with your boss. Welcome them, offer a drink, take their coat, show them a seat and make small talk until the boss is free.",
    roleB="You are the visitor. Accept a drink with *I'd like …*. Ask to see one thing: *I'd like to see the …* Make small talk about your journey.",
    script=[("Lena", "Good morning! Welcome to Greenline. You must be Mrs Rees."), ("Visitor", "Yes, hello. What a bright office!"), ("Lena", "Thank you. Can I take your coat? Please, have a seat."),
            ("Visitor", "Thanks."), ("Lena", "Would you like a coffee or a tea?"), ("Visitor", "I'd like a tea, please. Milk, no sugar."), ("Lena", "Of course. Help yourself to biscuits. Sam is coming in five minutes."),
            ("Visitor", "Perfect. And I'd like to see the new lamps, if that's OK."), ("Lena", "Of course — they're in the showroom.")],
    listen=[("Who is the visitor?", "Mrs Rees."), ("What does she drink?", "Tea with milk, no sugar."), ("When is Sam coming?", "In five minutes."), ("What would she like to see?", "The new lamps.")],
    mini="Student A welcomes Student B at reception: coat, seat, drink, biscuits. Student B says what they'd like. Swap. One minute.",
    pron="*Would you like …?* — *would you* joins: *wou-dyou*. *I'd like* — the *'d* is short but it's there; *I like a coffee* means something different. *WELcome!* — warm and strong.",
    ref="**Would you like …? / I'd like …** *Would you like* + noun (*a coffee*) or + *to* + verb (*to see the showroom*) makes a polite offer or invitation. *I'd like* (= *I would like*) + noun or + *to* + verb says politely what you want. Short answers: *Yes, please. No, thank you.* Compare *Do you like tea?* (in general) with *Would you like tea?* (now, an offer).",
)

C[15] = dict(
    match=[("goal", "something you want to do in the future"), ("course", "lessons on one subject"), ("skill", "something you can do well"),
           ("promotion", "a better job in the same company"), ("keep in touch", "stay in contact"), ("experience", "the things you have done in your work")],
    thread=("Lena's plan for next year", [
        "Next year I'm (1) ___ to take a marketing course, online, in the evenings.", "I want to (2) ___ new skills — video, mostly.",
        "I'm going to (3) ___ short videos with Tom in the warehouse.", "Sam is going to (4) ___ a small shop in Manchester, and I'm going to help.",
        "My (5) ___: a promotion in two years!", "And Ana is going to visit again in June — we're going to keep in (6) ___."],
        ["goal", "going", "learn", "make", "open", "touch"], ["going", "learn", "make", "open", "goal", "touch"]),
    form="*am / is / are* + *going to* + base verb: *I'm going to take a course. We're going to open a shop.* Negative: *isn't going to.* Question: *What are you going to do?*",
    use="Plans and intentions — things you have decided: *I'm going to make videos. He's going to be famous. Tom isn't going to like that!*",
    watch="*Going to* + base verb: *I'm going to take* ✓, *I'm going to taking* ✗. In speech it often sounds like *gonna* — but write *going to*.",
    practice=[("I ___ (take) a course next year.", "'m going to take"), ("What ___ you ___ (do)?", "are … going to do"), ("Tom ___ (not like) that!", "isn't going to like"),
              ("We ___ (open) a shop.", "'re going to open"), ("___ she going to be famous?", "Is"), ("They ___ (visit) us in June.", "'re going to visit")],
    gist=[("What is Lena going to do in the evenings?", "Take a marketing course, online."), ("What is Greenline going to do next year?", "Open a small shop in Manchester.")],
    controlled=[("It ___ great to see you. (was / is)", "was"), ("Have a good ___. (trip / travel)", "trip"), ("Let's ___ in touch. (keep / stay on)", "keep"),
                ("Message me ___ time. (any / every)", "any"), ("Say hi to Tom ___ me. (for / to)", "for"), ("See you ___! (soon / early)", "soon")],
    roleA="It's your review with Sam (Student B). Say three things you are going to do next year and one thing you aren't going to do. Then it's a colleague's last day: say goodbye and arrange how to keep in touch.",
    roleB="You are Sam. Ask *What are you going to do next?* and one more question. Then you are the colleague who is leaving: say goodbye, and say how you'll keep in touch.",
    script=[("Tom", "OK, Ben. Your last day! What are you going to do?"), ("Ben", "I'm going to work in Manchester — the new shop."), ("Tom", "Great. So we're going to see you."),
            ("Ben", "Every month! And I'm going to learn Spanish, for Ana's calls."), ("Tom", "Ha! It was great working with you. Have a good trip."), ("Ben", "Thanks. Let's keep in touch — message me any time."),
            ("Tom", "I will. Say hi to Manchester for me.")],
    listen=[("Where is Ben going to work?", "In the new shop in Manchester."), ("How often is Tom going to see him?", "Every month."), ("What is Ben going to learn, and why?", "Spanish, for Ana's calls."), ("How do they say they'll keep in touch?", "Message me any time.")],
    mini="Student A says three plans for next year with *going to*. Student B asks one question about each. Then say goodbye. Swap.",
    pron="*Going to* before a verb is quick and weak: *I'm gonna take a course* in speech. *Have a GOOD trip. Let's keep in TOUCH.* — warm, falling voice for a goodbye.",
    ref="**Going to.** *am / is / are* + *going to* + base verb. *I'm going to take a course. She's going to open a shop. They aren't going to come.* Question: *Are you going to …? What is he going to do?* Use it for plans and intentions you have already decided, and for predictions with evidence (*Look at the sky — it's going to rain*). For arrangements fixed in a diary, the present continuous (Unit 12) is also common: *We're meeting at nine.*",
)
