/* Block Camp: the end slide as a choice, not a wall.

   Innes, 2026-10-01: "make end screen with choice buttons to expand discuss
   and write". The activation slide's two cards (speaking in pairs, the
   writing task) used to stand side by side over the end clip. Now the word
   bank stays, and two big buttons, Discuss and Write, open one card at a
   time; a second tap closes it. Nothing is removed: the cards are the deck's
   own nodes, only shown and hidden, so the deck's translation, word count
   and Copy button keep working. Print shows both.

   Load with  <script src="block-camp/camp-end.js" defer></script>

   The second half of this file is the camp FLAG on the Results slide
   (Innes, 2026-10-02: "Users need some kind of achievement record of flags
   obtained from all the camps"). It lives here because every deck already
   loads this file and the decks themselves are not to be edited for it: it
   loads block-camp/camp-flags.js (generated by
   lesson-template/build/block-camp-flags/build.py) from this script's own
   folder, and when the Results slide becomes the active one it records the
   score and shows a small card - the flag, what just happened, and a link
   to block-camp/flags.html. */
(function () {
  'use strict';
  var slide = document.querySelector('.slide[data-type="activate"]');
  if (!slide || slide.querySelector('.act-choose')) return;
  var cols = slide.querySelector('.act-cols');
  var cards = cols ? [].slice.call(cols.querySelectorAll('.act-card')) : [];
  if (cards.length < 2) return;
  // Which card is which: the writing card is the one with the text box.
  var write = cards.filter(function (c) { return c.querySelector('textarea'); })[0] || cards[1];
  var speak = cards.filter(function (c) { return c !== write; })[0];

  var T = {
    en: ['Discuss', 'Write'], de: ['Sprechen', 'Schreiben'], es: ['Conversar', 'Escribir'],
    fr: ['Discuter', 'Écrire'], it: ['Discutere', 'Scrivere'], pt: ['Conversar', 'Escrever'],
    ru: ['Обсудить', 'Написать'],
    ar: ['ناقش', 'اكتب'],
    zh: ['讨论', '写作'], ja: ['話し合う', '書く']
  };

  var css = document.createElement('style');
  css.textContent =
    '.act-choose{display:flex;flex-wrap:wrap;gap:14px;margin:16px 0 4px}' +
    '.act-choice{display:inline-flex;align-items:center;gap:12px;min-height:58px;padding:0 26px;' +
    'border-radius:14px;cursor:pointer;font-family:var(--font-display);font-size:22px;letter-spacing:.02em;' +
    'color:var(--text);background:var(--surface2);background:color-mix(in srgb,var(--surface2) 86%,transparent);' +
    'border:2px solid color-mix(in srgb,var(--accent) 65%,transparent);transition:background .15s,color .15s,border-color .15s}' +
    '.act-choice .act-choice-i{font-size:24px;line-height:1}' +
    '.act-choice:hover,.act-choice:focus-visible{border-color:var(--accent);outline:none}' +
    '.act-choice[aria-expanded="true"]{background:var(--accent);color:var(--void);border-color:var(--accent)}' +
    '.act-choosing .act-cols{display:block!important}' +
    '.act-choosing .act-card{display:none!important}' +
    '.act-choosing .act-card.act-open{display:block!important;width:100%;max-width:none}' +
    // The card is full width now, so the box is too (it was sized for half).
    '.act-choosing .act-card.act-open .act-input{width:100%!important;max-width:none;min-height:120px;box-sizing:border-box}' +
    '@media print{.act-choose{display:none!important}.act-choosing .act-card{display:block!important}}';
  document.head.appendChild(css);

  var row = document.createElement('div');
  row.className = 'act-choose';
  row.setAttribute('role', 'group');
  function make(card, icon, key) {
    var b = document.createElement('button');
    b.type = 'button'; b.className = 'act-choice';
    b.setAttribute('aria-expanded', 'false');
    b.innerHTML = '<span class="act-choice-i" aria-hidden="true">' + icon + '</span><span class="act-choice-l"></span>';
    b._card = card; b._key = key;
    if (!card.id) card.id = 'act-card-' + key;
    b.setAttribute('aria-controls', card.id);
    b.addEventListener('click', function () { toggle(b); });
    row.appendChild(b);
    return b;
  }
  var bSpeak = make(speak, '🗣️', 0);
  var bWrite = make(write, '✍️', 1);
  cols.parentNode.insertBefore(row, cols);
  slide.classList.add('act-choosing');

  function toggle(b) {
    var opening = b.getAttribute('aria-expanded') !== 'true';
    [bSpeak, bWrite].forEach(function (x) {
      var on = opening && x === b;
      x.setAttribute('aria-expanded', on ? 'true' : 'false');
      x._card.classList.toggle('act-open', on);
    });
    if (opening) {
      // Bring the opened task into view on a scrolling (phone) slide.
      try { b._card.scrollIntoView({ block: 'nearest', behavior: 'smooth' }); } catch (_) {}
      var ta = b._card.querySelector('textarea');
      if (ta && !(window.matchMedia && matchMedia('(pointer: coarse)').matches)) ta.focus({ preventScroll: true });
    }
  }

  function label() {
    var lang = (document.documentElement.getAttribute('lang') || 'en').toLowerCase().slice(0, 2);
    var L = T[lang] || T.en;
    bSpeak.querySelector('.act-choice-l').textContent = L[0];
    bWrite.querySelector('.act-choice-l').textContent = L[1];
  }
  label();
  if (window.MutationObserver) new MutationObserver(label).observe(document.documentElement,
    { attributes: true, attributeFilter: ['lang'] });
})();

/* ── The flag card on the Results slide ──────────────────────────────────
   Score 50% on a camp's Part 1 (or a station) and its flag is planted; 75%
   and it goes gold; 50% on Part 2 adds a star. camp-flags.js holds the rule
   and the save; this half only listens for the Results slide and draws.
   Nothing here declares a name at the top level: the deck's engine owns
   score, maxScore, idx, slides, show, t... and is read through the DOM. */
(function () {
  'use strict';
  var res = document.querySelector('.slide[data-type="results"]');
  if (!res) return;
  var src = (document.currentScript && document.currentScript.src) || '';

  var T = {
    en: { planted: 'Camp {n} flag planted!', plantedSt: 'Station {n} flag planted!', gold: 'Gold flag!',
          star: 'Star added!', starSaved: 'Star saved!', flying: 'Your flag is flying',
          low: 'Score 50% to plant this camp’s flag', lowSt: 'Score 50% to plant this station’s flag',
          lowStar: 'Score 50% in Part 2 to add a star', starWait: 'Score 50% in Part 1 to plant the flag',
          toGold: 'Score 75% for a gold flag', best: 'Best: {p}%', link: 'Your flags' },
    de: { planted: 'Flagge für Camp {n} gesetzt!', plantedSt: 'Flagge für Station {n} gesetzt!', gold: 'Goldene Flagge!',
          star: 'Stern dazu!', starSaved: 'Stern gespeichert!', flying: 'Deine Flagge weht',
          low: 'Erreiche 50 %, um die Flagge dieses Camps zu setzen', lowSt: 'Erreiche 50 %, um die Flagge dieser Station zu setzen',
          lowStar: 'Erreiche 50 % in Teil 2 für einen Stern', starWait: 'Erreiche 50 % in Teil 1, um die Flagge zu setzen',
          toGold: 'Mit 75 % wird die Flagge golden', best: 'Bestwert: {p} %', link: 'Deine Flaggen' },
    es: { planted: '¡Bandera del campamento {n} plantada!', plantedSt: '¡Bandera de la estación {n} plantada!', gold: '¡Bandera de oro!',
          star: '¡Estrella añadida!', starSaved: '¡Estrella guardada!', flying: 'Tu bandera ondea',
          low: 'Consigue un 50 % para plantar la bandera de este campamento', lowSt: 'Consigue un 50 % para plantar la bandera de esta estación',
          lowStar: 'Consigue un 50 % en la Parte 2 para ganar una estrella', starWait: 'Consigue un 50 % en la Parte 1 para plantar la bandera',
          toGold: 'Con un 75 %, la bandera es de oro', best: 'Mejor: {p} %', link: 'Tus banderas' },
    fr: { planted: 'Drapeau du camp {n} planté !', plantedSt: 'Drapeau de la station {n} planté !', gold: 'Drapeau d’or !',
          star: 'Étoile ajoutée !', starSaved: 'Étoile gardée !', flying: 'Ton drapeau flotte',
          low: 'Obtiens 50 % pour planter le drapeau de ce camp', lowSt: 'Obtiens 50 % pour planter le drapeau de cette station',
          lowStar: 'Obtiens 50 % dans la partie 2 pour une étoile', starWait: 'Obtiens 50 % dans la partie 1 pour planter le drapeau',
          toGold: 'À 75 %, le drapeau devient or', best: 'Meilleur : {p} %', link: 'Tes drapeaux' },
    it: { planted: 'Bandiera del campo {n} piantata!', plantedSt: 'Bandiera della tappa {n} piantata!', gold: 'Bandiera d’oro!',
          star: 'Stella aggiunta!', starSaved: 'Stella salvata!', flying: 'La tua bandiera sventola',
          low: 'Fai il 50% per piantare la bandiera di questo campo', lowSt: 'Fai il 50% per piantare la bandiera di questa tappa',
          lowStar: 'Fai il 50% nella Parte 2 per una stella', starWait: 'Fai il 50% nella Parte 1 per piantare la bandiera',
          toGold: 'Con il 75% la bandiera diventa d’oro', best: 'Migliore: {p}%', link: 'Le tue bandiere' },
    pt: { planted: 'Bandeira do acampamento {n} fincada!', plantedSt: 'Bandeira da etapa {n} fincada!', gold: 'Bandeira de ouro!',
          star: 'Estrela adicionada!', starSaved: 'Estrela guardada!', flying: 'A sua bandeira está hasteada',
          low: 'Faça 50% para fincar a bandeira deste acampamento', lowSt: 'Faça 50% para fincar a bandeira desta etapa',
          lowStar: 'Faça 50% na Parte 2 para ganhar uma estrela', starWait: 'Faça 50% na Parte 1 para fincar a bandeira',
          toGold: 'Com 75%, a bandeira fica de ouro', best: 'Melhor: {p}%', link: 'As suas bandeiras' },
    ru: { planted: 'Флаг лагеря {n} установлен!', plantedSt: 'Флаг станции {n} установлен!', gold: 'Золотой флаг!',
          star: 'Звезда добавлена!', starSaved: 'Звезда сохранена!', flying: 'Твой флаг развевается',
          low: 'Набери 50%, чтобы установить флаг этого лагеря', lowSt: 'Набери 50%, чтобы установить флаг этой станции',
          lowStar: 'Набери 50% во второй части, чтобы получить звезду', starWait: 'Набери 50% в первой части, чтобы установить флаг',
          toGold: 'Набери 75% — флаг станет золотым', best: 'Лучший результат: {p}%', link: 'Твои флаги' },
    ar: { planted: 'رُفع علم المخيم {n}!', plantedSt: 'رُفع علم المحطة {n}!', gold: 'علم ذهبي!',
          star: 'أُضيفت نجمة!', starSaved: 'حُفظت النجمة!', flying: 'علمك يرفرف',
          low: 'احصل على 50% لترفع علم هذا المخيم', lowSt: 'احصل على 50% لترفع علم هذه المحطة',
          lowStar: 'احصل على 50% في الجزء 2 لتنال نجمة', starWait: 'احصل على 50% في الجزء 1 لترفع العلم',
          toGold: 'احصل على 75% لعلم ذهبي', best: 'الأفضل: {p}%', link: 'أعلامك' },
    zh: { planted: '营地 {n} 的旗帜已插上！', plantedSt: '第 {n} 站的旗帜已插上！', gold: '金旗！',
          star: '已添加星星！', starSaved: '星星已保存！', flying: '你的旗帜正在飘扬',
          low: '得分达到 50% 即可插上本营地的旗帜', lowSt: '得分达到 50% 即可插上本站的旗帜',
          lowStar: '第 2 部分得分达到 50% 可加一颗星', starWait: '第 1 部分得分达到 50% 即可插旗',
          toGold: '达到 75% 可得金旗', best: '最佳：{p}%', link: '你的旗帜' },
    ja: { planted: 'キャンプ{n}に旗を立てた！', plantedSt: 'ステーション{n}に旗を立てた！', gold: '金の旗！',
          star: '星を追加！', starSaved: '星を保存！', flying: '旗がはためいている',
          low: '50%取ると、このキャンプに旗を立てられる', lowSt: '50%取ると、このステーションに旗を立てられる',
          lowStar: 'パート2で50%取ると星がつく', starWait: 'パート1で50%取ると旗を立てられる',
          toGold: '75%で金の旗に', best: 'ベスト：{p}%', link: 'あなたの旗' }
  };

  var CSS =
    '.cf-card{display:inline-flex;align-items:center;gap:16px;margin:18px auto 0;padding:10px 20px 10px 12px;max-width:100%;' +
      'box-sizing:border-box;text-align:start;border-radius:var(--r,10px);color:var(--text);' +
      'background:var(--surface2);background:color-mix(in srgb,var(--surface2) 90%,transparent);' +
      'border:2px solid color-mix(in srgb,var(--accent) 45%,transparent)}' +
    '.cf-card.cf-win{border-color:var(--accent)}' +
    '.cf-card .cf-art{flex:none;width:64px;height:64px}' +
    '.cf-card .cf-art svg{display:block;width:64px;height:64px;overflow:visible}' +
    '.cf-card .cf-txt{display:grid;gap:2px;min-width:0;justify-items:start}' +
    '.cf-card .cf-t{font-family:var(--font-display);font-size:24px;font-weight:400;line-height:1.15;color:var(--text)}' +
    '.cf-card .cf-s{font-family:var(--font-ui);font-size:16px;line-height:1.3;color:var(--text-dim)}' +
    '.cf-card .cf-go{font-family:var(--font-ui);font-size:16px;line-height:1.3;color:var(--accent);text-decoration:none;white-space:nowrap}' +
    '.cf-card .cf-go:hover,.cf-card .cf-go:focus-visible{text-decoration:underline}' +
    'html.bc-phone .cf-card{gap:12px;margin-top:12px;padding:8px 14px 8px 8px}' +
    'html.bc-phone .cf-card .cf-art,html.bc-phone .cf-card .cf-art svg{width:48px;height:48px}' +
    'html.bc-phone .cf-card .cf-t{font-size:19px}' +
    'html.bc-phone .cf-card .cf-s,html.bc-phone .cf-card .cf-go{font-size:14px}' +
    'html.bc-phone .cf-card .cf-go{white-space:normal}' +
    '.cf-card.cf-plant .cf-art svg{animation:cf-drop .5s cubic-bezier(.3,1.6,.5,1) both}' +
    '.cf-card.cf-plant .cf-cloth{animation:cf-raise .9s steps(5,end) .35s both}' +
    '@keyframes cf-drop{from{transform:translateY(-16px);opacity:0}to{transform:none;opacity:1}}' +
    '@keyframes cf-raise{from{transform:translateY(5px)}to{transform:none}}' +
    '@media (prefers-reduced-motion:reduce){.cf-card.cf-plant .cf-art svg,.cf-card.cf-plant .cf-cloth{animation:none}}' +
    '@media print{.cf-card{display:none}}';

  var card = null, last = null, counted = false;

  function lang() { return (document.documentElement.getAttribute('lang') || 'en').toLowerCase().slice(0, 2); }
  function fmt(s, o) { return s.replace(/\{(\w)\}/g, function (_, k) { return o[k]; }); }
  function pc(x) { return Math.round((x || 0) * 100); }

  function words(r) {
    var L = T[lang()] || T.en, st = r.state, e = r.entry, camp = e.line === 'climb';
    var planted = fmt(camp ? L.planted : L.plantedSt, { n: e.n });
    var title, sub = [], win = false;
    if (r.part === 2) {
      if (r.newlyStar) { title = st.earned ? L.star : L.starSaved; win = true; if (!st.earned) sub.push(L.starWait); }
      else if (st.starSaved) { title = st.earned ? L.flying : L.starSaved; if (!st.earned) sub.push(L.starWait); }
      else title = L.lowStar;
      sub.push(fmt(L.best, { p: pc(st.best2) }));
    } else {
      if (r.newlyGold) { title = L.gold; win = true; if (r.newlyEarned) sub.push(planted); }
      else if (r.newlyEarned) { title = planted; win = true; sub.push(L.toGold); }
      else if (st.earned) { title = L.flying; if (!st.gold) sub.push(L.toGold); }
      else title = camp ? L.low : L.lowSt;
      sub.push(fmt(L.best, { p: pc(st.best) }));
    }
    return { title: title, sub: sub.join(' · '), win: win, link: L.link + (lang() === 'ar' ? ' ←' : ' →') };
  }

  function paint(fresh) {
    if (!card || !last) return;
    var w = words(last);
    card.querySelector('.cf-t').textContent = w.title;
    card.querySelector('.cf-s').textContent = w.sub;
    card.querySelector('.cf-go').textContent = w.link;
    if (fresh) {
      card.querySelector('.cf-art').innerHTML = window.CampFlags.sprite(last.entry, last.state, 64);
      card.classList.toggle('cf-win', w.win);
      card.classList.remove('cf-plant');
      if (w.win) { void card.offsetWidth; card.classList.add('cf-plant'); }
    }
  }

  function onResults() {
    var F = window.CampFlags;
    if (!F) return;
    var r = null;
    try { r = F.record({ countPlay: !counted }); } catch (_) {}
    counted = true;
    if (!r) { if (card && card.parentNode) card.parentNode.removeChild(card); card = null; return; }
    last = r;
    if (!card) {
      if (!document.getElementById('cf-card-css')) {
        var css = document.createElement('style'); css.id = 'cf-card-css'; css.textContent = CSS;
        document.head.appendChild(css);
      }
      card = document.createElement('div');
      card.className = 'cf-card';
      card.setAttribute('role', 'status');
      card.innerHTML = '<span class="cf-art"></span><span class="cf-txt"><b class="cf-t"></b><span class="cf-s"></span><a class="cf-go"></a></span>';
      card.querySelector('.cf-go').href = F.url('block-camp/flags.html');
      var msg = document.getElementById('scoreMsg');
      if (msg && res.contains(msg)) msg.parentNode.insertBefore(card, msg.nextSibling);
      else (res.querySelector('.slide-body') || res).appendChild(card);
    }
    paint(true);
  }

  function start() {
    if (!window.CampFlags) return;
    var on = res.classList.contains('is-active');
    if (on) onResults();
    if (window.MutationObserver) {
      // oldValue, not a remembered flag: leaving and coming back inside one
      // task (show(n-1); show(n)) arrives as one batch that ends where it began
      new MutationObserver(function (recs) {
        var now = res.classList.contains('is-active');
        var was = recs.length ? /(^|\s)is-active(\s|$)/.test(recs[0].oldValue || '') : on;
        var came = recs.some(function (m) { return !/(^|\s)is-active(\s|$)/.test(m.oldValue || ''); });
        if (now && (!was || came)) onResults();
        on = now;
      }).observe(res, { attributes: true, attributeFilter: ['class'], attributeOldValue: true });
      new MutationObserver(function () { paint(false); })
        .observe(document.documentElement, { attributes: true, attributeFilter: ['lang'] });
    }
  }

  if (window.CampFlags) { start(); return; }
  var s = document.createElement('script');
  // beside this file, wherever the deck is: the decks load block-camp/camp-end.js
  s.src = 'block-camp/camp-flags.js?v=1';
  try { if (src) s.src = new URL('camp-flags.js?v=1', src).href; } catch (_) {}
  s.onload = start;
  document.head.appendChild(s);
})();
