# -*- coding: utf-8 -*-
"""Build the five IELTS route pages from `tools/ielts_routes.py`.

    python3 tools/build_ielts_routes.py            # all six IELTS pages; then tools/seo.py
    python3 tools/build_ielts_routes.py --check    # exit 1 if any of the six is stale
    python3 tools/build_ielts_routes.py --force    # overwrite hand edits

`tools/build_hubs.py` runs the same thing (`build_all`), and so does
`tools/build_ielts_hub.py` from the command line: the route pages and the
landing page share their web-sized pictures in `ielts-hub/`, and a picture
that changes is re-cut and its old copy deleted, so they are always built
together or a page is left pointing at a deleted file.

WHY. The route pages were hand-written in the site's older IELTS design,
so the landing page (`ielts.html`, redesigned 2026-09-25) led into five
pages that looked like a different site, with a nav that had lost the
Level Check link and Free/Pro tags typed by hand. They now share the
landing page's palette, type, buttons and stop list — the `ih-` block from
`build_ielts_hub.py`, carried whole — and add only what a route page needs,
in an `ir-` block below it. The landing page is a chooser; a route page is
the full, described list for one paper, so it keeps every description and
teaching note and does not repeat the test-to-scale or the symptom list.

WHAT IS COMPUTED. Free and level come from the catalogue; counts, the
level span, the start button, "Start here", the free/Pro line and
Writing's "all but two end with writing you produce" are counted, never
typed. Lesson titles lose their "IELTS Academic Writing:" prefix here as on
the landing page (`build_ielts_hub.short_title`). Route order, number, name
and colour family come from `build_ielts_hub.ROUTES`; everything else about
a route from `tools/ielts_routes.py`. The picture is the same web-sized copy
the landing page uses (`ielts-hub/route-*.jpg`), cropped by `hero_pos`.

HAND EDITS ARE REFUSED. Each page carries the hash of what this builder
wrote. If a page has changed since (anything but the SEO fence and the
<title>, which `tools/seo.py` owns), or exists without the marker, nothing
is written — not that page, not the others, not the landing page — and the
run says which page and exits 2. Move the edit into `tools/ielts_routes.py`,
or run with --force if it is meant to go.
"""
import hashlib
import html
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import seo                                   # noqa: E402
import build_ielts_hub as hub                # noqa: E402

ROOT = seo.ROOT
SITE = seo.SITE
MARK = '<!-- IELTS-ROUTE: generated by tools/build_ielts_routes.py from tools/ielts_routes.py. Do not edit by hand. sha=%s -->'
MARK_RX = r'<!-- IELTS-ROUTE: generated by [^>]*? sha=([0-9a-f]{12}) -->\n?'

CSS = r"""<style id="ielts-route-css">
/* An IELTS route page. Generated by tools/build_ielts_routes.py. Everything
   ih- above is the landing page's own block, shared whole; this adds only
   what a route page needs. */
.ir-main { --ih-route: var(--ih-prod); }
.ir-main[data-family="recv"] { --ih-route: var(--ih-recv); }
.ir-main[data-family="lex"] { --ih-route: var(--ih-lex); }

/* ── hero: the landing page's route chapter, opened out ── */
.ir-hero { padding: clamp(28px, 4vw, 52px) 0 clamp(40px, 6vw, 72px); }
.ir-hero-in { display: grid; grid-template-columns: minmax(0, 6fr) minmax(0, 6fr); gap: clamp(28px, 5vw, 72px); align-items: center; }
.ir-crumb { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; margin: 0 0 26px;
  font-family: 'Barlow Condensed', sans-serif; font-weight: 700; letter-spacing: .12em; text-transform: uppercase; font-size: .8rem; color: var(--ih-text-dim); }
.ir-crumb a { color: var(--ih-text); text-decoration: none; border-bottom: 2px solid var(--ih-route); padding-bottom: 1px; }
.ir-crumb a:hover { color: var(--ih-accent-bright); }
.ir-head { display: flex; align-items: flex-end; gap: 18px; margin: 0 0 22px; }
.ir-num { font-family: 'Barlow Condensed', sans-serif; font-weight: 800; line-height: .78; letter-spacing: -.02em;
  font-size: clamp(4.2rem, 8vw, 7rem); color: var(--ih-route); }
.ir-head .ih-kicker { margin-bottom: 8px; }
.ir-h1 { font-family: 'Playfair Display', serif; font-weight: 900; margin: 0; line-height: .95; letter-spacing: -.02em;
  font-size: clamp(2.9rem, 6.2vw, 5rem); color: var(--ih-text); }
.ir-h1 small { display: block; font-size: .3em; letter-spacing: 0; line-height: 1.2; font-weight: 700; color: var(--ih-text-dim); margin-bottom: .35em; }
.ir-lede { font-size: clamp(1.04rem, 1.4vw, 1.14rem); line-height: 1.64; color: var(--ih-text-dim); margin: 0 0 14px; max-width: 58ch; text-wrap: pretty; }
.ir-lede strong { color: var(--ih-text); }
.ir-hero .ih-stats { margin-top: 22px; }
.ir-hero .ih-stats b { color: var(--ih-text); }
.ir-hero .ih-stats .ih-stat-free b { color: var(--ih-accent-bright); }
.ir-hero .ih-stats span { color: var(--ih-text-dim); }
/* a fixed 4:3 frame: stretched to the copy's height it became a tall slice
   that cropped out the subject the alt text names */
.ir-art { margin: 0; position: relative; border-radius: 18px; overflow: hidden; aspect-ratio: 4 / 3; align-self: center;
  background: var(--ih-sky); box-shadow: 0 24px 50px var(--ih-shadow); }
.ir-art img { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; }

/* ── the one thing to know first ── */
.ir-callout { background: var(--ih-card); border-top: 1px solid var(--ih-line); border-bottom: 1px solid var(--ih-line); }
.ir-callout p { margin: 0; padding: 22px 0 22px 22px; border-left: 4px solid var(--ih-route);
  font-size: 1.06rem; line-height: 1.62; color: var(--ih-text-dim); max-width: 88ch; }
.ir-callout strong { color: var(--ih-text); }

/* ── tracks ── */
.ir-tracks { background: var(--ih-card); padding: clamp(24px, 4vw, 48px) 0 clamp(48px, 7vw, 96px); }
.ir-track { display: grid; grid-template-columns: minmax(0, 4fr) minmax(0, 8fr); gap: clamp(24px, 5vw, 72px);
  padding: clamp(32px, 5vw, 60px) 0; border-bottom: 1px solid var(--ih-line); scroll-margin-top: 12px; }
.ir-track:last-child { border-bottom: 0; }
.ir-track-head { align-self: start; position: sticky; top: 24px; }
.ir-h2 { font-family: 'Playfair Display', serif; font-weight: 900; font-size: clamp(1.8rem, 3vw, 2.4rem);
  line-height: 1.08; letter-spacing: -.01em; margin: 0 0 12px; color: var(--ih-text); text-wrap: balance; }
.ir-track-note { margin: 0; font-size: .98rem; line-height: 1.55; color: var(--ih-text-dim); max-width: 36ch; }
.ir-stops { list-style: none; margin: 0; padding: 0; }
/* each lesson is a heading whose link is stretched over the whole row */
.ir-stop { position: relative; display: grid; grid-template-columns: 36px minmax(0, 1fr) auto; gap: 18px; align-items: start;
  padding: 16px 16px 16px 0; border-radius: 12px; color: var(--ih-text); transition: background .15s ease; }
.ir-stop + .ir-stop { border-top: 1px solid var(--ih-line); border-top-left-radius: 0; border-top-right-radius: 0; }
/* the line from this dot's centre to the next one's, whatever the row height */
.ir-stop:not(:last-child)::before { content: ''; position: absolute; left: 17px; top: 35px; height: 100%; width: 2px;
  background: color-mix(in srgb, var(--ih-route) 50%, transparent); }
.ir-stop:hover { background: color-mix(in srgb, var(--ih-paper) 70%, transparent); }
.ir-stop .ih-dot { width: 36px; height: 36px; font-size: 1.02rem; margin-top: 1px; }
.ir-stop:hover .ih-dot { transform: scale(1.1); }
.ir-stop-t { font-family: 'Playfair Display', serif; font-weight: 700; font-size: 1.28rem; line-height: 1.25; margin: 4px 0 6px; color: var(--ih-text); }
.ir-stop-t a { text-decoration: none; color: inherit; }
.ir-stop-t a::after { content: ''; position: absolute; inset: 0; border-radius: 12px; }
.ih .ir-stop-t a:focus-visible { outline: none; }
.ih .ir-stop-t a:focus-visible::after { outline: 3px solid var(--ih-accent); outline-offset: 2px; }
.ir-stop:hover .ir-stop-t a { text-decoration: underline; text-decoration-color: var(--ih-route); text-decoration-thickness: 2px; text-underline-offset: 4px; }
.ir-stop-d { margin: 0; font-size: 1rem; line-height: 1.6; color: var(--ih-text-dim); max-width: 64ch; }
.ir-tags { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; margin: 10px 0 0; }
.ir-tag { font-family: 'Barlow Condensed', sans-serif; font-weight: 700; letter-spacing: .08em; text-transform: uppercase;
  font-size: .72rem; line-height: 1; padding: 5px 9px 4px; border-radius: 999px; color: var(--ih-text-dim);
  border: 1px solid var(--ih-line); background: var(--ih-paper); }
.ir-tag-start { color: var(--ih-text); border-color: var(--ih-route); }
.ir-tags .ih-pill { font-size: .72rem; letter-spacing: .08em; padding: 5px 9px 4px; border: 1px solid var(--ih-accent); }
.ir-go { align-self: center; font-family: 'Barlow Condensed', sans-serif; font-weight: 700; letter-spacing: .1em;
  text-transform: uppercase; font-size: .82rem; color: var(--ih-text-dim); white-space: nowrap; transition: transform .15s ease, color .15s ease; }
.ir-stop:hover .ir-go { color: var(--ih-text); transform: translateX(3px); }

/* ── reference ── */
.ir-ref { padding: clamp(48px, 7vw, 88px) 0 0; }
@media (min-width: 861px) { .ir-ref .ih-bank-art { min-height: 300px; } }

/* ── notes, and the other routes ── */
.ir-notes { padding: clamp(48px, 7vw, 88px) 0 clamp(56px, 8vw, 104px); }
.ir-notes-grid { display: grid; grid-template-columns: minmax(0, 7fr) minmax(0, 5fr); gap: clamp(16px, 2.4vw, 28px); align-items: start; }
.ir-routes h2 { font-family: 'Playfair Display', serif; font-weight: 700; font-size: 1.36rem; margin: 0 0 12px; color: var(--ih-text); }
.ir-routes .ih-jump a[aria-current="page"] .ih-jump-name { text-decoration: underline; text-decoration-color: var(--ih-route); text-decoration-thickness: 3px; text-underline-offset: 5px; }
.ir-here { display: block; text-align: right; }
.ir-back { display: inline-block; margin-top: 16px; }
.ih-note .ir-note-h { font-family: 'Playfair Display', serif; font-weight: 700; font-size: 1.36rem; margin: 0 0 10px; color: var(--ih-text); }

.ir-close .ih-close-in { padding-top: clamp(56px, 8vw, 104px); padding-bottom: clamp(56px, 8vw, 104px); }
.ir-close .ih-h2 { font-size: clamp(1.9rem, 4vw, 2.9rem); }

@media (max-width: 900px) {
  .ir-hero-in { grid-template-columns: minmax(0, 1fr); }
  .ir-art { order: -1; aspect-ratio: 16 / 9; }
  .ir-track { grid-template-columns: minmax(0, 1fr); gap: 18px; }
  .ir-track-head { position: static; }
  .ir-notes-grid { grid-template-columns: minmax(0, 1fr); }
}
@media (max-width: 560px) {
  .ir-stop { grid-template-columns: 36px minmax(0, 1fr); gap: 14px; padding-right: 4px; }
  .ir-go { display: none; }
  .ir-head { gap: 12px; }
  .ir-h1 { font-size: clamp(2.3rem, 12vw, 2.9rem); }
}
@media (max-width: 380px) { .ir-num { font-size: 3.4rem; } }
</style>"""


def esc(s):
    return hub.esc(s)


def plain(s):
    return html.unescape(re.sub(r'<[^>]+>', '', s))


def and_list(xs):
    return xs[0] if len(xs) == 1 else ', '.join(xs[:-1]) + ' and ' + xs[-1]


def load(rows):
    """Every route, in build_ielts_hub.ROUTES order, each lesson annotated
    from the catalogue. Stops the build on anything it cannot render."""
    from ielts_routes import ROUTES as DATA
    data = {d['hub']: d for d in DATA}
    order = [r['hub'] for r in hub.ROUTES]
    if sorted(data) != sorted(order):
        sys.exit('! tools/ielts_routes.py has %s, build_ielts_hub.ROUTES has %s: they must list '
                 'the same route pages' % (sorted(data), sorted(order)))
    cat = {x['file']: x for x in rows}
    out, missing = [], []
    for i, meta in enumerate(hub.ROUTES):
        d = data[meta['hub']]
        r = dict(meta, **d, n=i + 1)
        r['tracks'] = [t for t in d['tracks'] if t['lessons']]
        if not r['tracks']:
            sys.exit('! %s has no lessons in tools/ielts_routes.py' % r['hub'])
        for ref in r.get('reference') or []:
            for l in ref['lessons']:
                if l['file'] != 'ielts-question-bank.html':
                    sys.exit('! %s: reference card %s has no design yet' % (r['hub'], l['file']))
        n = 0
        for t in r['tracks']:
            for l in t['lessons']:
                n += 1
                row = cat.get(l['file'])
                if row is None:
                    missing.append(l['file'])
                if not os.path.exists(os.path.join(ROOT, l['file'])):
                    sys.exit('! %s lists %s, which does not exist' % (d['hub'], l['file']))
                l.update(n=n, short=hub.short_title(l['title']),
                         free=bool(row) and row.get('access') != 'pro',
                         level=(row or {}).get('level') or '',
                         full=seo.clean(row['title'] if row else l['title']),
                         produces=hub.produces(l['file']))
        r['stops'] = [l for t in r['tracks'] for l in t['lessons']]
        free = [l for l in r['stops'] if l['free']]
        r['first'] = free[0] if free else r['stops'][0]
        if free and free[0] is not r['stops'][0]:
            print('  ! %s: the first lesson is not free; the start button goes to lesson %d'
                  % (r['hub'], free[0]['n']))
        out.append(r)
    for f in missing:
        print('  ! %s is on a route but not in the catalogue; shown as subscriber-only' % f)
    return out


def fill(text, r):
    """The placeholders a lede or a teaching note may use."""
    count = len(r['stops'])
    silent = [l['short'] for l in r['stops'] if not l['produces']]
    if silent:
        s = ('All but %s &mdash; %s &mdash; end with writing you actually produce rather than recognise.'
             % (hub.words(len(silent)), and_list(silent)) if len(silent) < count
             else 'None of them yet ends with writing you produce yourself.')
    else:
        s = 'Every one ends with writing you actually produce rather than recognise.'
    below = [l for l in r['stops'] if l['level'][:1] in ('A', 'B')]     # starts below C1
    levels = ('The whole set is C1' if not below else 'Everything is C1 except %s' % and_list(
        ['<em>%s</em>, which starts at %s' % (l['short'], l['level'][:2]) for l in below]))
    return (text.replace('{Count}', hub.words(count).capitalize())
                .replace('{count}', hub.words(count)).replace('{silent}', s)
                .replace('{levels}', levels))


def stop_html(l, start):
    tags = []
    if l['free']:
        tags.append('<span class="ih-pill">Free</span>')
    if start:
        tags.append('<span class="ir-tag ir-tag-start">Start here</span>')
    if l['level']:
        tags.append('<span class="ir-tag">%s</span>' % esc(l['level']))
    tags += ['<span class="ir-tag">%s</span>' % t for t in l['tags']]
    return ('        <li class="ir-stop%s">\n'
            '          <span class="ih-dot" aria-hidden="true">%d</span>\n'
            '          <div>\n'
            '            <h3 class="ir-stop-t"><a href="%s">%s</a></h3>\n'
            '            <p class="ir-stop-d">%s</p>\n'
            '            <p class="ir-tags">%s</p>\n'
            '          </div>\n'
            '          <span class="ir-go" aria-hidden="true">Open &rarr;</span>\n'
            '        </li>'
            % (' ih-free' if l['free'] else '', l['n'], seo.quote(l['file']), l['short'], l['desc'],
               '<span class="ih-vh">, </span>'.join(tags)))


def hero_html(r, routes):
    stops, first = r['stops'], r['first']
    free = [l for l in stops if l['free']]
    span = hub.level_span([l['level'] for l in stops])
    name = plain(first['short'])
    label = ('%s: %s' % ('Start free' if first['free'] else 'Start', first['short']) if len(name) <= 28
             else '%s with lesson %d' % ('Start free' if first['free'] else 'Start', first['n']))
    go = '<a class="ih-btn" href="%s">%s <span aria-hidden="true">&rarr;</span></a>' % (
        seo.quote(first['file']), label)
    stats = ['<li><b>%d</b><span>%s</span></li>' % (len(stops), hub.plural(len(stops), 'lesson'))]
    if len(r['tracks']) > 1:
        stats.append('<li><b>%d</b><span>tracks</span></li>' % len(r['tracks']))
    if free:
        stats.append('<li class="ih-stat-free"><b>%d</b><span>free%s</span></li>' % (
            len(free), ' &mdash; the first' if len(free) == 1 and free[0] is stops[0] else ''))
    art = hub.derive(r['art'], 'route-%s' % r['key'], 1200)
    return """<header class="ir-hero">
  <div class="ih-wrap ir-hero-in">
    <div class="ir-hero-copy">
      <nav class="ir-crumb" aria-label="Breadcrumb"><a href="ielts.html#routes">IELTS Academic</a><span aria-hidden="true">/</span><span>Route %(n)02d of %(of)02d</span></nav>
      <div class="ir-head">
        <span class="ir-num" aria-hidden="true">%(n)02d</span>
        <div>
          <p class="ih-kicker">%(kicker)s</p>
          <h1 class="ir-h1"><small>%(pre)s</small> %(name)s</h1>
        </div>
      </div>
%(ledes)s
      <ul class="ih-stats">%(stats)s</ul>
      <div class="ih-ctas">
        %(go)s
        <a class="ih-btn ih-btn-quiet" href="ielts.html#routes">All %(of_w)s routes</a>
      </div>
    </div>
    <figure class="ir-art"><img src="%(art)s" alt="%(alt)s" width="1200" height="672" fetchpriority="high" style="object-position:%(pos)s"></figure>
  </div>
</header>""" % dict(n=r['n'], of=len(routes), of_w=hub.words(len(routes)),
                   kicker='&nbsp;&middot;&nbsp;'.join(x for x in (r['module'], span) if x),
                   pre=r['h1'][0], name=r['h1'][1],
                   ledes='\n'.join('      <p class="ir-lede">%s</p>' % fill(p, r) for p in r['lede']),
                   stats=''.join(stats), go=go, art=art, alt=esc(html.unescape(r['art_alt'])),
                   pos=r.get('hero_pos') or r['pos'])


def tracks_html(r):
    out = []
    many = len(r['tracks']) > 1
    for i, t in enumerate(r['tracks']):
        n = len(t['lessons'])
        kick = ('Track %d of %d &middot; %d %s' % (i + 1, len(r['tracks']), n, hub.plural(n, 'lesson'))
                if many else 'In teaching order &middot; %d %s' % (n, hub.plural(n, 'lesson')))
        out.append("""  <section class="ir-track" id="track-%(i)d" aria-labelledby="ir-t%(i)d">
    <div class="ir-track-head">
      <p class="ih-kicker">%(kick)s</p>
      <h2 class="ir-h2" id="ir-t%(i)d">%(h)s</h2>
      <p class="ir-track-note">%(note)s</p>
    </div>
    <ol class="ir-stops">
%(stops)s
    </ol>
  </section>""" % dict(i=i + 1, kick=kick, h=t['h'], note=t['note'],
                       stops='\n'.join(stop_html(l, l is r['first']) for l in t['lessons'])))
    return '<div class="ir-tracks">\n<div class="ih-wrap">\n%s\n</div>\n</div>' % '\n'.join(out)


def reference_html(r):
    if not r.get('reference'):
        return ''
    n, t, types = hub.bank_numbers()
    cards = []
    for ref in r['reference']:
        for l in ref['lessons']:
            k = len(cards) + 1
            desc = l['desc'].replace('{bank}', '<b>%d Task&nbsp;2 questions across %d topics</b>' % (n, t))
            cards.append("""<section class="ir-ref" aria-labelledby="ir-ref-h%(k)d">
  <div class="ih-wrap">
    <a class="ih-bank-card" href="%(href)s">
      <div class="ih-bank-art"><img src="%(art)s" alt="" loading="lazy" decoding="async"></div>
      <div class="ih-bank-copy">
        <p class="ih-kicker">%(kick)s</p>
        <h2 id="ir-ref-h%(k)d">%(title)s</h2>
        <p>%(desc)s</p>
        <ul class="ih-types">%(types)s</ul>
        <span class="ih-btn">Open the question bank <span aria-hidden="true">&rarr;</span></span>
      </div>
    </a>
  </div>
</section>""" % dict(k=k, href=seo.quote(l['file']), art=hub.derive(hub.BANK_SRC, 'bank', 1200),
                     kick=ref['note'].capitalize(), title=l['title'], desc=desc,
                     types=''.join('<li>%s</li>' % esc(x) for x in types)))
    return '\n'.join(cards)


def notes_html(r, routes):
    jump = '\n'.join(
        '        <li data-family="%s"><a href="%s"%s><span class="ih-jump-n">%02d</span>'
        '<span class="ih-jump-name">%s</span><span class="ih-jump-c">%d %s%s</span></a></li>'
        % (x['family'], x['hub'], ' aria-current="page"' if x is r else '', x['n'], x['name'],
           len(x['stops']), hub.plural(len(x['stops']), 'lesson'),
           '<span class="ir-here" aria-hidden="true">you are here</span>' if x is r else '')
        for x in routes)
    t = r['teach']
    teach = ''
    if t:
        teach = """    <div class="ih-note">
      <h2 class="ir-note-h">%s</h2>
%s
    </div>""" % (t['h'], '\n'.join('      <p>%s</p>' % fill(p, r) for p in t['p']))
    return """<section class="ir-notes" aria-label="For teachers, and the other routes">
  <div class="ih-wrap ir-notes-grid">
%(teach)s
    <nav class="ir-routes" aria-labelledby="ir-routes-h">
      <h2 id="ir-routes-h">All %(of_w)s IELTS routes</h2>
      <ol class="ih-jump">
%(jump)s
      </ol>
      <a class="ih-textlink ir-back" href="ielts.html">The IELTS landing page</a>
    </nav>
  </div>
</section>""" % dict(teach=teach, jump=jump, of_w=hub.words(len(routes)))


def close_html(r, series):
    stops = r['stops']
    free = sum(1 for l in stops if l['free'])
    pro = len(stops) - free
    if free and pro:
        head = '%s %s free. Pro opens the other %s.' % (
            hub.words(free).capitalize(), 'lesson on this route is' if free == 1 else 'lessons on this route are',
            hub.words(pro))
        lead = 'Free lessons need no account. '
    elif free:
        head = 'Every lesson on this route is free.'
        lead = ''
    else:
        head = 'Every lesson on this route comes with Pro.'
        lead = ''
    art = ('<img class="ih-close-art" src="%s" alt="" loading="lazy" decoding="async">\n  ' % series
           if series else '')
    return """<section class="ih-close ir-close" aria-labelledby="ir-close-h">
  %s<div class="ih-close-in">
    <p class="ih-kicker">Forbes English Pro</p>
    <h2 class="ih-h2" id="ir-close-h">%s</h2>
    <p>%sPro is every lesson on the site &mdash; IELTS and everything else &mdash; with new ones as they are published.</p>
    <div class="ih-ctas">
      <a class="ih-btn" href="pricing.html">Plans and prices <span aria-hidden="true">&rarr;</span></a>
      <a class="ih-btn ih-btn-quiet" href="library.html#cat=IELTS">Every IELTS lesson in the library</a>
    </div>
  </div>
</section>""" % (art, head, lead)


def ld(r):
    name = plain(' '.join(r['h1']))
    return {'@context': 'https://schema.org', '@graph': [
        {'@type': 'BreadcrumbList', 'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': SITE + '/index.html'},
            {'@type': 'ListItem', 'position': 2, 'name': 'IELTS Academic', 'item': SITE + '/ielts.html'},
            {'@type': 'ListItem', 'position': 3, 'name': name}]},
        {'@type': 'ItemList', 'name': '%s lessons, in teaching order' % name,
         'numberOfItems': len(r['stops']),
         'itemListElement': [
             {'@type': 'ListItem', 'position': l['n'],
              'url': '%s/%s' % (SITE, seo.quote(l['file'])), 'name': l['full']}
             for l in r['stops']]}]}


def chrome():
    """The first stylesheet, the font links and the top band, from ielts.html
    — the same lift build_hubs.py does — so the nav cannot drift again. The
    IELTS tab is the current section here, not the current page."""
    src = open(os.path.join(ROOT, 'ielts.html'), encoding='utf-8').read()
    style = re.search(r'<style>.*?</style>', src, re.S).group(0)
    fonts = '\n'.join(re.findall(r'<link[^>]+(?:preconnect|fonts\.googleapis)[^>]*>', src))
    nav = re.search(r'<nav class="topband">.*?</nav>', src, re.S).group(0)
    nav = nav.replace(' aria-current="page"', ' aria-current="true"')
    return style, fonts, nav


def page(r, routes, series, seo_block, title):
    style, fonts, nav = chrome()
    main = '\n'.join(x for x in (
        '<main class="ir-main" data-family="%s">' % r['family'],
        hero_html(r, routes),
        '<div class="ir-callout" role="note"><div class="ih-wrap"><p>%s</p></div></div>'
        % r['callout'] if r.get('callout') else '',
        tracks_html(r), reference_html(r), notes_html(r, routes), close_html(r, series),
        '</main>') if x)
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>%(title)s</title>
%(seo)s
%(fonts)s
%(style)s
%(hubcss)s
%(css)s
</head>
<body class="ih ir">
%(mark)s
%(nav)s

%(main)s
<script type="application/ld+json">%(ld)s</script>
</body>
</html>
""" % dict(title=title, seo=seo_block, fonts=fonts, style=style, hubcss=hub.css(), css=CSS,
           mark='%MARK%', nav=nav, main=main,
           ld=json.dumps(ld(r), ensure_ascii=False, separators=(',', ':')))


def _owned(src):
    """The page minus the parts other tools own: the SEO fence and <title>
    (tools/seo.py) and the marker line itself."""
    src = re.sub(re.escape(seo.START) + '.*?' + re.escape(seo.END), '', src, flags=re.S)
    src = re.sub(r'<title>.*?</title>', '', src, flags=re.S)
    return re.sub(MARK_RX, '', src)


def _sha(src):
    return hashlib.sha1(_owned(src).encode('utf-8')).hexdigest()[:12]


def build(rows=None, images=None, check=False, force=False):
    """Build the five route pages. All or nothing: if any page was edited by
    hand (or has lost its marker) and force is off, write nothing at all and
    return it in `refused`. Returns (stale, refused)."""
    hub.STATE.update(check=check, missing=[])
    if rows is None:
        rows, source = seo.lessons(write_cache=not check)
        print('  lessons: %d (from %s)' % (len(rows), source))
    if images is None:
        images = seo.lesson_images()
    routes = load(rows)
    out, refused = [], []
    for r in routes:
        path = os.path.join(ROOT, r['hub'])
        old = open(path, encoding='utf-8').read() if os.path.exists(path) else ''
        m = re.search(MARK_RX, old)
        if old and not force:
            if m and m.group(1) != _sha(old):
                refused.append(r['hub'])
                print('  ! %s was edited by hand since it was generated. Move the change into '
                      'tools/ielts_routes.py, or re-run with --force to discard it.' % r['hub'])
                continue
            if not m:
                refused.append(r['hub'])
                print('  ! %s has no generator marker, so it may hold hand-written content. '
                      'Re-run with --force to replace it.' % r['hub'])
                continue
        out.append((r, path, old))
    if refused and not force:
        print('  ! nothing written: the six IELTS pages are built together or not at all.')
        return True, refused
    series = hub.mosaic(routes, images)
    stale = []
    for r, path, old in out:
        seo_m = re.search(re.escape(seo.START) + '.*?' + re.escape(seo.END), old, re.S)
        title_m = re.search(r'<title>.*?</title>', old, re.S)
        new = page(r, routes, series,
                   seo_m.group(0) if seo_m else '%s\n%s' % (seo.START, seo.END),
                   title_m.group(0)[7:-8] if title_m else 'IELTS %s | Forbes English' % r['name'])
        new = new.replace('%MARK%', MARK % _sha(new.replace('%MARK%\n', '')), 1)
        if new != old:
            stale.append(r['hub'])
            if not check:
                open(path, 'w', encoding='utf-8', newline='\n').write(new)
        print('  %-22s %2d lessons, %d free, %s%s' % (
            r['hub'], len(r['stops']), sum(1 for l in r['stops'] if l['free']),
            plain(hub.level_span([l['level'] for l in r['stops']])) or '-',
            (' — STALE' if check else ' — rewritten') if r['hub'] in stale else ' — unchanged'))
    for m in hub.STATE['missing']:
        print('  ! %s would be written' % m)
    return bool(stale) or bool(hub.STATE['missing']), refused


def build_all(rows=None, images=None, check=False, force=False):
    """The five route pages, then the landing page, which links into them
    and shares their pictures. The landing page is not touched if a route
    page was refused. Returns (stale, refused)."""
    if rows is None:
        rows, source = seo.lessons(write_cache=not check)
        print('  lessons: %d (from %s)' % (len(rows), source))
    if images is None:
        images = seo.lesson_images()
    stale, refused = build(rows, images, check=check, force=force)
    if refused:
        return stale, refused
    return hub.build(rows, images, check=check) or stale, refused


if __name__ == '__main__':
    check = '--check' in sys.argv
    failures = hub.contrast_report()
    stale, refused = build_all(check=check, force='--force' in sys.argv)
    if refused:
        sys.exit(2)
    if failures:
        sys.exit('! %d contrast pair(s) fail' % failures)
    if check and stale:
        sys.exit(1)
