# -*- coding: utf-8 -*-
"""Forbes English — IELTS Writing Task 2 question bank: the source data.

`ielts-question-bank.html` is generated from this file by
`tools/build_ielts_bank.py`. Edit here, run the builder, never hand-edit the
page — the counts in the title, the meta description and the filter chips are
all derived, so a hand edit silently makes them wrong.

**The arguments are written as mechanisms, not slogans.** "People are more
independent" is a trend wearing an explanation's costume: a candidate cannot
build a paragraph on it. A usable argument says what causes what, so it can be
extended, and so it can be disagreed with. Keep that bar when adding topics.

Each topic carries three arguments each way. They are not required to balance
in strength — some questions genuinely have a stronger side — but both columns
have to be arguable, because half the prompts ask the candidate to discuss
both views.
"""

TYPES = {
 'opinion':   ('Opinion',          'To what extent do you agree?'),
 'discussion':('Discussion',       'Discuss both views and give your own opinion.'),
 'outweigh':  ('Outweigh',         'Do the advantages outweigh the disadvantages?'),
 'measure':   ('Problem & measure','What problems… and what measures?'),
 'direct':    ('Direct question',  'Two questions in one prompt.'),
}

TOPICS = [
{
 'id':'education', 'name':'Education',
 'blurb':'The single most common topic on the paper.',
 'prompts':[
  ('Universities should only offer subjects that are useful in the future job market, such as science and technology. To what extent do you agree or disagree?','opinion'),
  ('Some people believe children should begin formal schooling at six years old. Others argue that four is better. Discuss both views and give your own opinion.','discussion'),
  ('In many countries, final examinations are being replaced by continuous assessment throughout the year. Do the advantages of this change outweigh the disadvantages?','outweigh'),
  ('The number of students who leave university before completing their degree has risen sharply in many countries. What problems does this cause, and what measures could reduce it?','measure'),
  ('More adults are returning to full-time education later in life. Why is this happening, and do you think it is a positive or a negative development?','direct'),
  ('Some argue that schools should teach practical life skills such as cooking and personal finance in place of some traditional academic subjects. To what extent do you agree?','opinion'),
  ('Some schools are replacing printed textbooks with tablets and laptops. Do the advantages of this change outweigh the disadvantages?','outweigh'),
  ('In some countries, teachers are paid less than other professionals with similar qualifications. What problems does this cause, and what could be done about it?','measure'),
 ],
 'for_h':'Arguments for narrowing education toward useful skills',
 'for':[
  'Graduates in shortage fields earn a measurable wage premium, and the state recovers part of it through tax — so the training pays for itself in a way a general degree may not.',
  'Employers in engineering, nursing and the trades report vacancies left open for months for want of specific technical training, while unrelated graduates are unemployed. That is a matching failure, not a shortage of education.',
  'A degree that leads to no particular job still leaves the debt. The cost falls hardest on students whose families cannot absorb three unpaid years.',
 ],
 'against_h':'Arguments against narrowing it',
 'against':[
  'Many of the fastest-growing occupations of the last decade did not exist when their current workers chose a subject. Training for a named job is training for a moving target.',
  'The abilities employers name most often — writing clearly, holding an argument, reading quickly and sceptically — are produced mainly by the subjects usually called useless.',
  'A university that serves only the current labour market stops doing the research that creates the next one. Its value is partly the part that has no immediate use.',
 ],
},
{
 'id':'environment', 'name':'Environment',
 'blurb':'Almost always paired with cost, responsibility or growth.',
 'prompts':[
  ('Some people believe that individuals should be responsible for reducing their own carbon emissions, while others argue this is a job for governments alone. Discuss both views and give your own opinion.','discussion'),
  ('Many cities are restricting or banning private cars from their central areas. Do the advantages of this development outweigh the disadvantages?','outweigh'),
  ('Protecting the environment should be the responsibility of the countries that became wealthy by polluting. To what extent do you agree?','opinion'),
  ('Household waste is increasing in many countries despite recycling schemes. Why is this happening, and what measures could reverse it?','measure'),
  ('More people are choosing to eat less meat than in the past. Why is this change happening, and is it a positive development?','direct'),
  ('Some believe environmental problems are now too large for individual nations to solve and require international agreement. To what extent do you agree?','opinion'),
  ('Some believe the best way to protect endangered species is to ban all human activity in their habitats; others argue local people must be allowed to earn a living there. Discuss both views and give your own opinion.','discussion'),
  ('Water shortages are becoming more common in many regions. What are the causes, and what measures could governments take?','measure'),
 ],
 'for_h':'Arguments for placing the duty on individuals',
 'for':[
  'Household choices — heating, driving, flying, diet — account for a large share of national emissions, and no government can change them without the household agreeing.',
  'A policy nobody supports is repealed at the next election, so individual willingness is what makes government action survive a change of party.',
  'Demand moves supply faster than regulation does: firms reformulate products when sales fall, and that takes months rather than the years a law takes to pass.',
 ],
 'against_h':'Arguments for placing it on government',
 'against':[
  'The largest emitting systems — the electricity grid, freight, building standards — are not consumer choices at all. No amount of individual care rewires a country.',
  'Asking individuals to act alone creates a collective-action problem: the person who sacrifices pays the full cost and receives a share of the benefit too small to measure.',
  'The framing was itself promoted by the industries with most to lose from regulation, which is a reason to be suspicious of it rather than to adopt it.',
 ],
},
{
 'id':'technology', 'name':'Technology & work',
 'blurb':'Devices, screens and the workplace — artificial intelligence has its own topic.',
 'prompts':[
  ('Some companies now let their employees decide for themselves how many days a week they work from home. To what extent do you agree that this decision should be left to the individual employee?','opinion'),
  ('More and more people work entirely from home. Do the advantages of this development outweigh the disadvantages?','outweigh'),
  ('Some believe that automation will create more jobs than it destroys; others predict lasting unemployment. Discuss both views and give your own opinion.','discussion'),
  ('Many employees report finding it harder to concentrate at work than a decade ago. What problems does this cause, and what measures could help?','measure'),
  ('Fewer young people are learning to drive than twenty years ago. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Employers should be allowed to monitor what their staff do on company computers. To what extent do you agree?','opinion'),
  ('Some people spend most of their free time looking at a screen. What problems can this cause, and what could be done to reduce them?','measure'),
  ('Online shopping has replaced high-street shops in many towns. Do the advantages of this outweigh the disadvantages?','outweigh'),
 ],
 'for_h':'Arguments that technology improves working life',
 'for':[
  'Removing the commute returns between one and two hours a day to the worker — time that was previously unpaid and is now theirs, which is a real pay rise nobody records as one.',
  'Remote hiring widens the pool beyond one city, which raises wages in places that previously had one large employer and no competition for staff.',
  'Automating a task nobody wanted to do is how every previous generation of work improved. The loom, the spreadsheet and the dishwasher all destroyed jobs people were glad to stop doing.',
 ],
 'against_h':'Arguments that it damages it',
 'against':[
  'The work that most needs proximity is the work nobody schedules: training a new colleague, repairing a disagreement, developing an idea nobody has yet put into words.',
  'The benefit is unevenly distributed. A senior employee with a spare room gains; a junior one in a shared flat loses both the desk and the informal learning that came with sitting near someone experienced.',
  'Historically the jobs destroyed and the jobs created have not gone to the same people, or to the same towns. The aggregate can improve while a specific place does not recover for a generation.',
 ],
},
{
 'id':'ai', 'name':'Artificial intelligence',
 'blurb':'The newest topic on the paper, and the one candidates have least ready-made language for.',
 'prompts':[
  ('Artificial intelligence is now able to do work that once required a university degree. Do the advantages of this development outweigh the disadvantages?','outweigh'),
  ('Some believe students should be allowed to use artificial intelligence to help write their assignments; others think it should be banned outright. Discuss both views and give your own opinion.','discussion'),
  ('Artificial intelligence should never be used to make decisions about who gets a job, a loan or a place at university. To what extent do you agree or disagree?','opinion'),
  ('Many people now get their news and advice from artificial intelligence rather than from journalists or experts. What problems can this cause, and what measures could reduce them?','measure'),
  ('More companies are using artificial intelligence to answer customer questions instead of employing people. Why is this happening, and do you think it is a positive or a negative development?','direct'),
  ('Governments should slow the development of artificial intelligence until its effects are better understood. To what extent do you agree?','opinion'),
  ('Some argue that artificial intelligence will make creative work such as writing, music and design less valuable; others believe it will make it more valuable. Discuss both views and give your own opinion.','discussion'),
  ('Artificial intelligence is being used to diagnose illness in some hospitals. Do the advantages of this outweigh the disadvantages?','outweigh'),
 ],
 'for_h':'Arguments that AI is a net gain',
 'for':[
  'The work it takes over first is the work people describe as the worst part of their job — sorting records, drafting boilerplate, reading through a thousand near-identical documents. Removing it does not remove the job; it removes the part nobody wanted to do.',
  'A model applies the same rule to every case. A tired human assessor at four in the afternoon does not, and the difference between the first and the last file of the day is measurable. Consistency is itself a fairness argument.',
  'It lowers the price of expertise in places that never had any. A clinic with no radiologist within two hundred miles is not choosing between a machine and a specialist; it is choosing between a machine and nothing.',
 ],
 'against_h':'Arguments that it is a net loss',
 'against':[
  'A system trained on past decisions reproduces the pattern in those decisions. If a company’s previous hires skewed one way, the model learns that skew as if it were a rule — and hands it back with the authority of arithmetic.',
  'Expertise is built by doing the easy cases badly and being corrected. Automate the junior work and you keep this year’s experts while quietly removing the way the next ones were made.',
  'When a decision cannot be explained, it cannot be appealed. A refusal you can argue with is a different thing from a refusal that arrives as an output, and the second one moves the power in the room.',
 ],
},
{
 'id':'work', 'name':'Work & careers',
 'blurb':'Distinct from technology: this is about the shape of a working life.',
 'prompts':[
  ('People change jobs and careers far more often than they used to. Do the advantages of this outweigh the disadvantages?','outweigh'),
  ('Some believe that a high salary is the most important factor in choosing a job; others say job satisfaction matters more. Discuss both views and give your own opinion.','discussion'),
  ('Employers should give older workers the same opportunities for training and promotion as younger ones. To what extent do you agree?','opinion'),
  ('Many young people find it difficult to get their first job. What are the causes, and what measures could help?','measure'),
  ('More people are choosing to work for themselves rather than for an employer. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Companies should be required to publish the pay of every role they advertise. To what extent do you agree?','opinion'),
  ('Some argue that unpaid internships give young people valuable experience; others believe they should be banned. Discuss both views and give your own opinion.','discussion'),
  ('Many employees report working longer hours than their contracts require. What problems does this cause, and what could be done about it?','measure'),
 ],
 'for_h':'Arguments that the modern working life is better',
 'for':[
  'A worker who can leave has bargaining power a worker who cannot does not. Mobility is not only a preference — it is the mechanism that forces an employer to improve conditions rather than merely to advertise them.',
  'Skills built in one industry now transfer to several, so a downturn in one sector no longer ends a career. The person who once had a single employer and a single trade had no second option when either failed.',
  'Flexible arrangements let people who were previously excluded — carers, disabled workers, those far from a city — take work that a fixed office made impossible. The labour force gets larger rather than merely rearranged.',
 ],
 'against_h':'Arguments that it is worse',
 'against':[
  'Training is an investment, and an employer only makes it if the worker is likely to still be there. High turnover makes it rational for every firm to train less, which leaves the whole workforce less skilled than any individual firm intended.',
  'Pensions, sick pay and parental leave were built on the assumption of a long stay in one place. Move often enough and the entitlements never mature, so the risk quietly transfers from the company to the person.',
  'Work that can be done anywhere can be done by anyone, anywhere. The same flexibility that frees an employee also removes the local scarcity that gave them their wage.',
 ],
},
{
 'id':'health', 'name':'Health & society',
 'blurb':'Usually about who pays, and who decides.',
 'prompts':[
  ('In many countries people are living longer, and the number of adults over seventy is rising rapidly. What problems does this cause, and what measures could be taken to address them?','measure'),
  ('Some believe governments should tax unhealthy food; others argue people should be free to eat what they choose. Discuss both views and give your own opinion.','discussion'),
  ('Healthcare should be free at the point of use for everyone, regardless of income. To what extent do you agree?','opinion'),
  ('Rates of physical activity among young people have fallen in many countries. Why is this happening, and what measures could reverse it?','measure'),
  ('More people are living alone than ever before. Why is this happening, and do you think it is a positive or a negative development?','direct'),
  ('Some argue that hospitals should prioritise patients whose illnesses were not caused by their own choices. To what extent do you agree?','opinion'),
  ('Some argue that mental health should receive the same funding as physical health. To what extent do you agree?','opinion'),
  ('Fewer people cook at home than a generation ago. Why is this happening, and is it a positive or a negative development?','direct'),
 ],
 'for_h':'Arguments for state responsibility for health',
 'for':[
  'Illness is not distributed by choice: the strongest predictor of poor health outcomes is income at birth, which nobody selects.',
  'Treating a condition early is cheaper than treating its emergency, so a system that removes the price at the door often costs the state less overall, not more.',
  'A workforce that cannot afford treatment works while ill, which spreads infection and lowers output — the cost simply moves somewhere it is harder to see.',
 ],
 'against_h':'Arguments for individual responsibility',
 'against':[
  'A service that is free at the door has no signal to ration demand, so it rations by waiting instead — and long waits fall hardest on people who cannot take time off.',
  'Some of the largest costs follow from choices made repeatedly over decades, and a system that never mentions this removes any reason to change them.',
  'Public money spent on health is money not spent on the housing, air quality and transport that determine health long before a hospital is involved.',
 ],
},
{
 'id':'ageing', 'name':'Population & ageing',
 'blurb':'A demographic question dressed as an opinion one.',
 'prompts':[
  ('In many countries the proportion of older people is rising quickly. What problems does this cause, and what measures could governments take?','measure'),
  ('Some believe the retirement age should rise as life expectancy rises; others say people should be free to stop working at sixty. Discuss both views and give your own opinion.','discussion'),
  ('Adult children should be legally required to support their elderly parents. To what extent do you agree?','opinion'),
  ('Fewer people are having children in many wealthy countries. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Some countries encourage immigration to offset a falling birth rate. Do the advantages of this outweigh the disadvantages?','outweigh'),
  ('Governments should pay people to have more children. To what extent do you agree?','opinion'),
  ('Some argue that older people should make room for younger ones in senior jobs; others say experience should decide. Discuss both views and give your own opinion.','discussion'),
  ('More older people are living in care homes rather than with their families. What problems can this cause, and what could be done about it?','measure'),
 ],
 'for_h':'Arguments that an ageing population is manageable',
 'for':[
  'The dependency figure counts people by age, not by what they do. Raise participation among the healthy over-sixties even slightly and the ratio that looks alarming on paper changes materially.',
  'Older workers leaving is not the only variable: output per worker has risen for two centuries, and a smaller workforce producing more is not the same crisis as a smaller workforce producing the same.',
  'A shrinking population reduces pressure on housing, land and emissions — the very problems the same governments are otherwise spending heavily to solve.',
 ],
 'against_h':'Arguments that it is a serious problem',
 'against':[
  'Pension and health systems were funded on the assumption that each generation would be larger than the last. When it is not, the shortfall does not appear gradually; it appears as a specific bill in a specific decade.',
  'Care work cannot be automated at the rate the shortfall requires, and it is precisely the sector already unable to recruit. The gap is in hands, not in money.',
  'Political weight follows numbers. As the electorate ages, spending shifts toward the old and away from schools and housing — which suppresses the birth rate further and deepens the original problem.',
 ],
},
{
 'id':'family', 'name':'Family & society',
 'blurb':'Change over a generation — usually with a judgement attached.',
 'prompts':[
  ('In many countries people are having children much later in life than they used to. Why is this happening, and do you think it is a positive or a negative development?','direct'),
  ('Some believe grandparents should play a large part in raising children; others think parents should manage alone. Discuss both views and give your own opinion.','discussion'),
  ('Working parents should be given the right to work flexible hours. To what extent do you agree?','opinion'),
  ('People in many cities report knowing few of their neighbours. What problems does this cause, and what measures could help?','measure'),
  ('More people are moving away from the town they grew up in. Do the advantages of this outweigh the disadvantages?','outweigh'),
  ('Some argue that children today have too little unsupervised time. To what extent do you agree?','opinion'),
  ('In many countries, adult children are living with their parents for longer. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Some argue that both parents should be entitled to the same amount of paid leave after a child is born. To what extent do you agree?','opinion'),
 ],
 'for_h':'Arguments that these changes are gains',
 'for':[
  'Later parenthood usually follows from something people wanted: finished study, secure work, a chosen partner rather than an available one.',
  'Mobility means a person is no longer limited to the jobs, or the company, that happen to exist in their birthplace — which is the main route out of a declining town.',
  'Households that no longer have to hold together for want of an alternative are households where staying is a choice, and that is a change in favour of the weaker party.',
 ],
 'against_h':'Arguments that they are losses',
 'against':[
  'Later parenthood narrows the window and raises the chance of ending up with fewer children than intended, or none — a cost paid privately and rarely counted.',
  'Dispersed families move childcare and elderly care from something relatives absorbed to something that must be bought, which lands hardest on those who cannot buy it.',
  'A neighbourhood where nobody stays long has nobody who notices when something is wrong, and that kind of loose attention is difficult to replace with a service.',
 ],
},
{
 'id':'cities', 'name':'Cities & housing',
 'blurb':'Space, cost and who a city is built for.',
 'prompts':[
  ('In many cities, ordinary workers can no longer afford to live near their jobs. What problems does this cause, and what measures could reduce it?','measure'),
  ('Some believe governments should build more housing; others argue they should improve transport so people can live further out. Discuss both views and give your own opinion.','discussion'),
  ('Cities should invest in public transport rather than in new roads. To what extent do you agree?','opinion'),
  ('More people are moving from the countryside into cities. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Some cities are converting streets in their centres into parks and pedestrian areas. Do the advantages of this outweigh the disadvantages?','outweigh'),
  ('Old buildings should be protected even when the land could be used for much-needed housing. To what extent do you agree?','opinion'),
  ('Some argue that living in a large city is better for young people; others believe a small town is better. Discuss both views and give your own opinion.','discussion'),
  ('Many people spend more than two hours a day travelling to and from work. What problems does this cause, and what could be done about it?','measure'),
 ],
 'for_h':'Arguments for building denser, taller cities',
 'for':[
  'The cost of a home is set mainly by how many exist near the jobs. Any policy that does not change that number is redistributing the shortage rather than ending it.',
  'Density is what makes a bus route, a clinic or a school viable. Below a certain number of people per square kilometre these services stop paying for themselves and the state withdraws them.',
  'A short commute is not a convenience; it is hours of life returned each week, and the health effects of long daily travel are measurable in ways that a housing statistic is not.',
 ],
 'against_h':'Arguments against unlimited density',
 'against':[
  'Building faster than the sewers, schools and trains can absorb produces a place that is crowded and underserved at the same time. The infrastructure has a longer lead time than the housing, and it is rarely funded first.',
  'A city that replaces everything old with something profitable loses the thing that made people want to be there. The character is an asset with no line in the accounts, so it is spent first.',
  'Green space per resident falls as density rises, and it falls fastest for the people with the smallest homes — exactly those with the least private space to make up the difference.',
 ],
},
{
 'id':'travel', 'name':'Travel & tourism',
 'blurb':'Reliably paired with cost, culture or the environment.',
 'prompts':[
  ('Tourism brings money to poorer regions but often damages the places visitors come to see. Do the advantages of tourism outweigh the disadvantages?','outweigh'),
  ('Some believe international travel broadens the mind; others argue that most tourists learn nothing about the countries they visit. Discuss both views and give your own opinion.','discussion'),
  ('Air travel should be taxed much more heavily to reduce the number of flights. To what extent do you agree?','opinion'),
  ('Some historic cities receive far more visitors than they can comfortably hold. What problems does this cause, and what measures could be taken?','measure'),
  ('More people are choosing to holiday in their own country rather than abroad. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Governments should limit the number of tourists allowed to visit fragile natural sites. To what extent do you agree?','opinion'),
  ('Some argue that tourism preserves local traditions by making them profitable; others say it turns them into performances. Discuss both views and give your own opinion.','discussion'),
  ('Many young people take a year away from study or work to travel. Do the advantages of this outweigh the disadvantages?','outweigh'),
 ],
 'for_h':'Arguments that tourism is worth its costs',
 'for':[
  'Tourist money reaches people that other kinds of investment do not — a guide, a driver, a family letting rooms. It is one of the few industries where earnings land directly in a household rather than passing through a company first.',
  'A building that earns nothing gets demolished. Visitor revenue is often the only reason a town can justify maintaining a monument it would otherwise let fall down.',
  'Meeting a place is a poor substitute for living in it, but it is a better one than reading about it. Countries whose people travel are measurably less willing to believe the crudest things said about their neighbours.',
 ],
 'against_h':'Arguments that the costs are too high',
 'against':[
  'When visitors can outbid residents for the same rooms, housing stops being housing. The centre of the city empties of the people whose lives were the thing the visitors came to see.',
  'Tourism income arrives seasonally and vanishes in a crisis. A region that has rebuilt its whole economy around it has swapped a diversified living for a single, weather-dependent one.',
  'The environmental cost is concentrated exactly where the asset is. A reef, a trail or a glacier can absorb a certain number of feet per year, and the number of feet is set by an airline’s pricing rather than by the site.',
 ],
},
{
 'id':'crime', 'name':'Crime & justice',
 'blurb':'Punishment, prevention and cause.',
 'prompts':[
  ('Some people believe prison sentences should be longer to deter crime; others argue that education and employment do more. Discuss both views and give your own opinion.','discussion'),
  ('Rates of some crimes have fallen in many countries while fear of crime has risen. Why is this happening, and is it a problem?','direct'),
  ('The main purpose of prison should be rehabilitation rather than punishment. To what extent do you agree?','opinion'),
  ('Reoffending rates remain high in many countries. What problems does this cause, and what measures could reduce it?','measure'),
  ('Some argue that widespread surveillance cameras in public places make cities safer. Do the advantages outweigh the disadvantages?','outweigh'),
  ('Young offenders should be treated differently from adults who commit the same crime. To what extent do you agree?','opinion'),
  ('Some believe that the causes of crime are mainly economic; others argue they are mainly cultural. Discuss both views and give your own opinion.','discussion'),
  ('Some countries publish the names and photographs of convicted criminals. Do the advantages of this practice outweigh the disadvantages?','outweigh'),
 ],
 'for_h':'Arguments for punishment and deterrence',
 'for':[
  'A sentence removes the specific individual from the situation for a fixed period, which prevents the offences they would otherwise have committed in that time.',
  'Consistent, visible consequences are what makes a rule a rule; where enforcement is unpredictable, the calculation shifts in favour of offending.',
  'Victims have a claim on the outcome that is independent of what happens to the offender afterwards, and a system that ignores it loses public consent.',
 ],
 'against_h':'Arguments for rehabilitation and prevention',
 'against':[
  'Deterrence depends on the perceived chance of being caught far more than on the length of the sentence, so raising sentences changes the arithmetic the offender is not doing.',
  'A prison term interrupts employment, housing and family at once, and the reoffending rate reflects that a person released without any of the three has few options.',
  'The countries with the lowest reoffending rates spend most on what happens after release, which suggests the useful variable is resettlement rather than severity.',
 ],
},
{
 'id':'money', 'name':'Government & money',
 'blurb':'Tax, spending and what the state is for.',
 'prompts':[
  ('Some people believe university education should be funded entirely by the state. Others argue that students should pay the full cost of their own degrees. Discuss both views and give your own opinion.','discussion'),
  ('Governments should spend money on public services rather than on the arts. To what extent do you agree?','opinion'),
  ('Some countries are considering a shorter working week with no reduction in pay. Do the advantages outweigh the disadvantages?','outweigh'),
  ('The gap between the highest and lowest earners has widened in many countries. What problems does this cause, and what measures could narrow it?','measure'),
  ('Fewer people carry cash than a decade ago. Why is this happening, and is it a positive development?','direct'),
  ('Wealthy countries should give a fixed share of their income as aid to poorer ones. To what extent do you agree?','opinion'),
  ('Some argue that a country’s success should be measured by the wellbeing of its people rather than by economic growth. To what extent do you agree?','opinion'),
  ('Many people now retire much later than their parents did. Why is this happening, and is it a positive or a negative development?','direct'),
 ],
 'for_h':'Arguments for higher public spending',
 'for':[
  'Some goods cannot be bought individually at any price — clean air, a functioning court, a road network — and only collective purchase produces them at all.',
  'Public investment in training and infrastructure raises private productivity later, so part of what looks like spending is a transfer across time rather than a cost.',
  'Where a service is left to the market, the people priced out of it do not stop needing it; the cost reappears as emergency provision, which is dearer.',
 ],
 'against_h':'Arguments for restraint',
 'against':[
  'Money raised in tax was going to be spent by someone anyway; the case has to be that the state will spend it better, and that is a claim requiring evidence rather than assumption.',
  'Public programmes are far easier to start than to stop, so a spending decision commits future governments who were not part of it.',
  'High marginal rates change behaviour at the margin: they alter where firms locate and how much people work, and those effects are slow, real and hard to reverse.',
 ],
},
{
 'id':'media', 'name':'Media & culture',
 'blurb':'Attention, tradition and who decides what is worth keeping.',
 'prompts':[
  ('Some believe that social media has done more harm than good to public debate. To what extent do you agree?','opinion'),
  ('Governments should fund the preservation of traditional culture even when few people take part in it. Discuss both views and give your own opinion.','discussion'),
  ('Some argue that global entertainment is eroding local culture. Do the disadvantages outweigh the advantages?','outweigh'),
  ('People in many countries report reading fewer books than they did a decade ago. Why is this happening, and what measures could change it?','measure'),
  ('Museums and galleries in many cities now charge no entrance fee. Why has this become common, and is it a positive development?','direct'),
  ('Advertising aimed at children should be banned. To what extent do you agree?','opinion'),
  ('Some believe that news should be free to everyone; others argue that good journalism has to be paid for. Discuss both views and give your own opinion.','discussion'),
  ('Celebrities are given far more attention than people who do important work. What problems does this cause, and what could be done about it?','measure'),
 ],
 'for_h':'Arguments that open media is a gain',
 'for':[
  'The cost of publishing fell to near zero, which ended the position of a small number of editors deciding what an entire country was permitted to read.',
  'Movements that no newspaper would have covered have organised and been heard, and several were vindicated only after they had already been dismissed.',
  'Minority languages and small local traditions now reach audiences too scattered to have ever supported a printed edition.',
 ],
 'against_h':'Arguments that it is a loss',
 'against':[
  'Attention is now sold rather than earned, and the material that holds attention best is not the material that informs best — outrage travels further than correction.',
  'Removing the editor removed the person who checked; the correction, when it comes, reaches a fraction of those who saw the original.',
  'Where everyone can publish, the scarce resource becomes trust, and a public that cannot tell sources apart tends to disbelieve all of them equally.',
 ],
},
{
 'id':'language', 'name':'Language & globalisation',
 'blurb':'A favourite of examiners, and one candidates often answer with slogans.',
 'prompts':[
  ('The spread of English as a global language is putting smaller languages at risk. Do the disadvantages of this outweigh the advantages?','outweigh'),
  ('Some believe children should learn a foreign language from the age of five; others think it should wait until secondary school. Discuss both views and give your own opinion.','discussion'),
  ('Governments should spend money on keeping minority languages alive. To what extent do you agree?','opinion'),
  ('Fewer students in English-speaking countries are choosing to study foreign languages. Why is this happening, and what measures could change it?','measure'),
  ('Many people now use translation software instead of learning a language. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Every country should have one official language. To what extent do you agree?','opinion'),
  ('Some argue that a global language brings people closer together; others believe it mainly benefits the countries that already speak it. Discuss both views and give your own opinion.','discussion'),
  ('Some schools now teach subjects such as science and history in a foreign language. Do the advantages of this outweigh the disadvantages?','outweigh'),
 ],
 'for_h':'Arguments that a shared global language is a gain',
 'for':[
  'A common language lowers the cost of every transaction across a border — research, trade, treatment, rescue. The saving is invisible precisely because the failure it prevents never happens.',
  'It gives a speaker from a small country access to an audience their own language could never reach. The alternative is not equality between languages; it is being read by very few people.',
  'Scientific and medical knowledge moves fastest when it does not have to be re-translated at every border. Delay in that pipeline has a body count, which is not true of most cultural losses.',
 ],
 'against_h':'Arguments that the loss is serious',
 'against':[
  'A language carries distinctions that no other language makes — kinship terms, plant names, ways of marking time. When it goes, the knowledge encoded in those distinctions goes with it, and it is not recoverable from a dictionary.',
  'If the language of advancement is not the language of the home, children are sorted by their parents’ fluency before they are sorted by their own ability. The shared language becomes a filter rather than a bridge.',
  'A country whose best work is published in someone else’s language gradually stops producing serious writing in its own. The decline is not a ban; it is a slow withdrawal of reasons to bother.',
 ],
},
{
 'id':'food', 'name':'Food & consumption',
 'blurb':'Cost, health and waste — usually with a policy question attached.',
 'prompts':[
  ('A large amount of the food produced in the world is thrown away. What are the causes, and what measures could reduce it?','measure'),
  ('Some believe supermarkets should be banned from selling food that has travelled long distances; others say the choice should be left to shoppers. Discuss both views and give your own opinion.','discussion'),
  ('Governments should require restaurants to display the calorie content of every dish. To what extent do you agree?','opinion'),
  ('More people are buying ready-made meals instead of cooking from raw ingredients. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Growing food locally rather than importing it is better for a country. Do the advantages outweigh the disadvantages?','outweigh'),
  ('Advertising for food high in sugar and fat should be banned completely. To what extent do you agree?','opinion'),
  ('Some argue that eating together as a family is important; others say it matters less than it used to. Discuss both views and give your own opinion.','discussion'),
  ('In many countries, healthy food costs more than unhealthy food. What problems does this cause, and what could be done about it?','measure'),
 ],
 'for_h':'Arguments for regulating what people eat',
 'for':[
  'The cost of diet-related illness is paid by everyone through taxes and waiting lists, so the decision is not purely private even when the meal is. Where a cost is shared, a say in it is not an intrusion.',
  'A choice made under an advertising budget of billions is not a free choice in any useful sense. Regulation here does not remove a decision; it removes a thumb from the scale.',
  'Labelling and pricing rules work on the poorest fastest, because they are the people with the least room to absorb a bad purchase. The effect is largest where the need is greatest.',
 ],
 'against_h':'Arguments against it',
 'against':[
  'Taxes on food are regressive by construction: the same levy takes a larger share of a small income than a large one, so the policy hits hardest the people it was written to protect.',
  'People substitute rather than stop. Tax one product and consumption moves to the next one along, which is why the measured health gain from these schemes is usually far smaller than the projection.',
  'Diet is one of the last areas where people on low incomes still make their own decisions. Removing that is a real cost, even if it does not appear in a health statistic.',
 ],
},
{
 'id':'sport', 'name':'Sport & leisure',
 'blurb':'Money, participation and what free time is for.',
 'prompts':[
  ('Some believe top athletes are paid far too much; others argue their salaries reflect what audiences will pay. Discuss both views and give your own opinion.','discussion'),
  ('Governments should spend money encouraging ordinary people to exercise rather than supporting elite sport. To what extent do you agree?','opinion'),
  ('Fewer children play organised sport than a generation ago. What are the causes, and what measures could reverse it?','measure'),
  ('Many cities spend large sums hosting international sporting events. Do the advantages of this outweigh the disadvantages?','outweigh'),
  ('More adults are taking part in extreme or endurance sports. Why is this happening, and is it a positive or a negative development?','direct'),
  ('Competitive sport should be a compulsory part of every school timetable. To what extent do you agree?','opinion'),
  ('Some argue that watching sport brings a community together; others say it simply replaces taking part. Discuss both views and give your own opinion.','discussion'),
  ('Some countries pay large sums to bring foreign athletes into their national teams. Do the advantages of this outweigh the disadvantages?','outweigh'),
 ],
 'for_h':'Arguments for public money in sport',
 'for':[
  'Facilities are the constraint, not enthusiasm. Where a pool or a pitch closes, participation in that area falls and does not recover when a campaign tells people to be more active.',
  'The health saving is slow but compounding: a person who keeps a habit into their fifties costs the health service far less across the following twenty years than one who does not.',
  'Sport is one of the few settings where children from different backgrounds are mixed by ability rather than by postcode. Remove it and the sorting happens somewhere less benign.',
 ],
 'against_h':'Arguments against it',
 'against':[
  'The measured benefit of hosting a major event is almost always smaller than the bid promised, and the stadium is maintained for decades by a city that has stopped using it.',
  'Money spent at the elite end reaches a few hundred people. The same sum spent on school facilities reaches tens of thousands, and the two are usually presented as if they were the same policy.',
  'Compulsion produces attendance, not habit. Adults who disliked school sport are measurably less likely to exercise later, which is the opposite of what the requirement was for.',
 ],
},
{
 'id':'science', 'name':'Science & research',
 'blurb':'Funding, ethics and what research is for.',
 'prompts':[
  ('Some argue that money spent exploring space would be better spent solving problems on Earth. To what extent do you agree?','opinion'),
  ('Some believe scientific research should be funded by governments; others say private companies should pay for it. Discuss both views and give your own opinion.','discussion'),
  ('Using animals in medical research is sometimes necessary. Do the advantages of this outweigh the disadvantages?','outweigh'),
  ('Fewer young people are choosing to study science at university in some countries. What are the causes, and what measures could change it?','measure'),
  ('Scientists are increasingly expected to explain their work to the public. Why is this happening, and is it a positive or a negative development?','direct'),
  ('The results of publicly funded research should be free for anyone to read. To what extent do you agree?','opinion'),
  ('Some argue that research should focus on immediate practical problems; others believe curiosity-driven work matters more. Discuss both views and give your own opinion.','discussion'),
  ('Some countries offer large payments to attract scientists from abroad. Do the advantages of this outweigh the disadvantages?','outweigh'),
 ],
 'for_h':'Arguments for funding research generously and freely',
 'for':[
  'The applications that pay for a field are rarely the ones it was funded to find. The laser, the web and the MRI scanner were all side effects of work that had no stated use at the time.',
  'Research is a fixed cost paid once and copied for nothing. A result that took twenty years to establish can be used by every country on Earth the following morning, which is a return no factory can match.',
  'Work that is not published cannot be checked. Open results are not a courtesy to readers; they are the mechanism by which a wrong finding gets caught before it is built on.',
 ],
 'against_h':'Arguments for restraint or redirection',
 'against':[
  'Money is not free-floating: a budget granted to one field is a budget refused to another, and the comparison is usually made against other research rather than against the clinic or the school it actually displaced.',
  'When a private company pays, it owns the result and can price it. Publicly funded work that ends in a patented product has been paid for twice by the same people.',
  'A country that recruits scientists rather than training them is drawing down another country’s investment. The gain is real, but it is a transfer, not an increase.',
 ],
},
]
